### ISSUE TITLE
Allow list-item action slots to have an independent disabled state form the list-item

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-design-system#5664] opened 2022-10-28 20:37 UTC
### Description

The use case is that a list item (GP tool) is disabled, but we want to show an information icon that the user can interact with either on hover / click to give help to the user on why this item (GP tool) is disabled. This would occur when the licensing is not sufficient to use the tool and we need to direct them to information on getting the license / seeing more information about the licensing level.

Right now, the actions inherit the disabled state from the list-item, so there is no way to provide user interaction on those actions.

### Acceptance Criteria

The scope of the issue would be the list-item respecting the `disabled` attribute on itself and any slotted actions independently.

### Relevant Info
![image](https://user-images.githubusercontent.com/52869490/198727917-3deddbac-3ec5-451b-8549-45db2e4404fd.png)
![image](https://user-images.githubusercontent.com/52869490/198727952-6272e011-ccb0-41e8-abe0-455af941410f.png)

### Which Component

calcite-list-item

### Example Use Case

https://codepen.io/eborgen/pen/WNyvagJ

### Esri team

ArcGIS Map Viewer

**Comment by driskull** [comment] 2022-10-28 20:55
@jcfranco @benelan @eriklharper  What are your thoughts about how disabling could work here?

- Would we introduce another property to disable only the content of a list item?
  - `content-disabled`?
  - Would we introduce a mode? `disableMode="content";  // probably not its ugly.
- Would we update `disabled` to not affect slotted actions? If so, a user would have to disable them separately.
  - If we do this, we would need to update the interaction helper to not set pointer-events for the whole component.

Other ideas?

**Comment by benelan** [comment] 2022-10-28 21:02
@geospatialem any a11y concerns with a disabled component having non-disabled child(ren)?

**Comment by geospatialem** [comment] 2022-10-28 22:21
> @geospatialem any a11y concerns with a disabled component having non-disabled child(ren)?

@benelan This sounds like a very solid use case. From the a11y perspective, its not a known or expected pattern, so would need to consult with a few other a11y professionals to determine the best path forward on the enhancement. Can report back here in a few weeks once a few of us can convene together.

**Comment by driskull** [comment] 2022-10-28 22:28
Yeah if we disable the component it will get `aria-disabled` on the host. I'm not sure if that will affect slotted children or not.

**Comment by nattarnoff** [comment] 2022-11-09 22:04
Disabled is not a valid attribute on the `<li>`. What needs to happen here is the disabled attribute needs to be applied to the button. It is also preferred to use this attribute over the aria-disabled attribute.
`<li>`
  `<button disabled><span>ICON</span> TITLE</button>`
  `<button class="tooltip" aria-label="NAME">icon</button><button class="tooltip" aria-label="NAME">icon</button>`
`</li>`

This will allow you to disabled the control but allow the tooltips and other icon buttons to still be accessible.

**Comment by karl9006** [comment] 2022-11-14 16:43
@driskull @geospatialem Please refer to Nat's response above.

**Comment by driskull** [comment] 2022-11-14 17:34
@nattarnoff I'm not following your comment. I don't see a `disabled` attribute added to any `li` within the `calcite-list-item`. There is no `<li>` used internally on that component.

**Comment by driskull** [comment] 2022-11-14 18:53
Since the "content" button is internal to the component and not slotted, we would need to be able to disable via a prop or something like that if we want to support this without breaking changes.

**Comment by nattarnoff** [comment] 2022-11-15 14:04
@driskull as the `calcite-list-item` has `role="listitem"` on it, it IS a ` li `as far as the browser and assistive technology are concerned. Therefore, you cannot put `disabled ` or `aria-disabled` on it. Those should be located on the items inside the listitem.

**Comment by driskull** [comment] 2022-11-15 16:45
> Therefore, you cannot put disabled or aria-disabled on it. Those should be located on the items inside the listitem.

Its also a custom element, so we can put `disabled` on it because we define that attribute as a custom attribute. `disabled` is not a global reserved attribute so we can use that name for the custom component `calcite-list-item`.

As for the `aria-disabled`. We do this for all of our components we we add our `disabled` attribute on them. cc @jcfranco
If we need to change that part, we can. From what I understand, we can add `aria-disabled` to any element regardless of the role. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled

> Another reason to need use the aria-disabled attribute over the HTML disabled attribute is if you have created custom controls which need to be marked as disabled, but are not using an element that allows for the disabled attribute.

**Comment by nattarnoff** [comment] 2022-11-21 14:42
@driskull I went through the Codepen at the top of the description. The problem with how it is written now is that the second icon in the first `calcite-list-item` isn't tabbable despite being a `button` and having `aria-disabled="false"`. If you navigate by arrows, you find that it announces as a button, but is unavailable. 
![image](https://user-images.githubusercontent.com/379104/203078899-3e51154b-9b15-466b-844b-f8d71a99f132.png)

From the first description paragraph of the linked MDN article (emphasis mine): 

> The `aria-disabled` attribute, when set to `true`, _indicates that the element upon which it is set and all of its focusable descendants are meant to be in the disabled state_. This declaration will inform people using assistive technologies, such as screen readers, that such elements are not meant to be editable or otherwise operable.

Aria-disabled cascades. Once set, the children cannot be unset. Putting these attributes on the container and not the controls causes problems. I've put together a sample using a basic UL to demonstrate: https://codepen.io/nattarnoff/pen/dyeVgdV?editors=1111

You still need to move the attributes from the parent (rendered `LI`) to the rendered controls (`button`). This is what the AT is concerned about regardless if the control is built using a JS framework like Calcite or native HTML.

**Comment by driskull** [comment] 2022-11-21 17:40
> I went through the Codepen at the top of the description. The problem with how it is written now is that the second icon in the first calcite-list-item isn't tabbable despite being a button and having aria-disabled="false". If you navigate by arrows, you find that it announces as a button, but is unavailable.

Yes, it's working as designed right now. If a component is disabled, all things inside it are disabled as well.  I think we would need to engineer a way to disable only specific parts of the component. If we need to rethink how this is engineered, we can do that.

> You still need to move the attributes from the parent (rendered LI) to the rendered controls (button). This is what the AT is concerned about regardless if the control is built using a JS framework like Calcite or native HTML.

I think it's up to the user to disable anything they slot into the component. Since they can slot custom components like `calcite-action`, we don't know all the things that may need to be disabled.  In this case, the user would need to set `disabled` on the `calcite-action` as well. We could try to query for known slotted components and disable them but I'd prefer to not modify the light DOM in these cases.

**Comment by nwhittaker** [comment] 2023-02-24 19:01
The Field Maps web app is looking to use the list component for listing and selecting layers. In some cases a layer is not selectable, but we still want to be able to perform actions on it (e.g. "Delete"), or show accessible error iconography w/ tooltips.

**Comment by jcfranco** [comment] 2023-03-17 19:12
@ethanbdev, @nwhittaker Could you provide info on priority/impact for this?

**Comment by nwhittaker** [comment] 2023-03-17 20:40
>Could you provide info on priority/impact for this?

This issue is one of several that are blocking an effort in Field Maps Designer to refactor the list of layers and group-layers as a `<calcite-list>`:
- https://github.com/Esri/calcite-components/issues/6537
- https://github.com/Esri/calcite-components/issues/6546
- https://github.com/Esri/calcite-components/issues/6574
- https://github.com/Esri/calcite-components/issues/6544

Our current implementation is a combination of custom components and `<calcite-tree>` elements. We'd like to migrate to the `<calcite-list>` element because it provides built-in filtering, more action/content slots, and grouping/nesting. The impact of moving to this element is that it would hopefully streamline the code and improve the consistency, maintainability, and testability of our layers list UI.

For prioritization, our refactoring issue is beginning to block other issues (that would like to make use of the `list-item` slots) that are slated for the Summer release (6/27). I imagine we have some flexibility, though, if that date's not feasible.

**Comment by ethanbdev** [comment] 2023-03-17 21:06
For web analysis, its blocking a design to communicate licensing information to users.

I would put p3 - want for upcoming milestone if @nwhittaker agrees or wants to put it higher

**Comment by geospatialem** [comment] 2023-03-30 18:22
A pattern will be established and should be part of a convention update when decided upon.

**Comment by nwhittaker** [comment] 2023-12-07 16:13
Just curious why this issue was closed? The reported problem still exists in `calcite-list-item` elements: https://codepen.io/nwhittaker-esri/pen/oNmmMKb.

In this repro, I'd expect the first item's action to be accessible.

**Comment by geospatialem** [comment] 2023-12-07 21:43
> Just curious why this issue was closed? The reported problem still exists in `calcite-list-item` elements: https://codepen.io/nwhittaker-esri/pen/oNmmMKb.
> 
> In this repro, I'd expect the first item's action to be accessible.

Thanks for flagging this, @nwhittaker! 

Reopening this issue, but blocking the effort as a result of https://github.com/Esri/calcite-design-system/issues/8373, which will be a more robust new component that can support `list-item`s, and other similar components, which contain a `heading` and `description`. While there is a [solution available for _some_ lists](https://codepen.io/geospatialem/pen/qBgggpY), it doesn't support cases where a `heading` and `description` is provided, and there are some alignment issues.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/6f21c189-76ba-4643-a8a6-05f7a1e5e3c3)

**Comment by jcfranco** [comment] 2024-02-29 22:37
This came up recently and we'll be exploring an option to list items to not be interactive (w/o using `disabled`). This should help with the provided use case and also allow `disabled` to behave consistently across components (preventing interaction with the element and any respective children).

**Comment by macandcheese** [comment] 2024-07-17 17:52
+1 from UC

**Comment by driskull** [comment] 2024-07-17 17:56
Maybe we should add a property like `contentDisabled` which won't disable interaction but will look disabled?

I'm not sure if it should also prevent selection of the item (just allow actions to be accessed). We could have another prop for `selection-disabled` if we want to separate them.

**Comment by macandcheese** [comment] 2024-07-17 19:59
Yeah I think that’s a nice clean solution and one that should be easy for users to opt-in to. Whether it’s multiple booleans or a single property with multiple values, either way sounds good.

**Comment by driskull** [comment] 2024-07-18 23:38
@ashetland @SkyeSeitz @jcfranco any thoughts here?

I think we should proceed with a `content-disabled` property that will just make the content area visually disabled (add opacity to the content area).

**Comment by SkyeSeitz** [comment] 2024-07-18 23:52
Agreed with moving forward with a `content-disabled` prop to disable interaction on everything (including selection) on the `calcite-list-item` expect for slotted actions. Was there need for `content-disabled` to still allow for selection at this time?

**Comment by ashetland** [comment] 2024-07-19 15:01
With `content-disabled`, if slotted Actions still function, would the drag handle and the expand buttons also still function?

**Comment by driskull** [comment] 2024-07-19 15:36
> prop to disable interaction on everything (including selection) on

I think in some cases selection may still want to function. Maybe we shouldn't disable this.

**Comment by ashetland** [comment] 2024-07-19 17:13
Throwing this out there, could this be addressed via tokens to set the opacity on the container (or some other way to accomplish this)? If it's not actually disabling anything, and is only a visual treatment, then I'm not sure this prop makes sense.

**Comment by driskull** [comment] 2024-07-19 17:20
> Throwing this out there, could this be addressed via tokens to set the opacity on the content container (or some other way to accomplish this)? If it's not actually disabling anything, and is only a visual treatment, then I'm not sure this prop makes sense.

Yes, it could. However, that would mean anyone that wants do to this would have to all set the same opacity number or color value. I could see some inconsistency arise here.

If the name is an issue, we could find something better than `content-disabled` like `inactive`

I don't think this should prevent selection because there are use cases where the item should still be selectable to open a related panel.

**Comment by ashetland** [comment] 2024-07-19 17:24
+1 for `inactive`

**Comment by driskull** [comment] 2024-07-19 17:56
@jcfranco thoughts?

Can we proceed with `inactive` to set the content to look disabled.

If a further use case arrives for `selection-disabled` we can address it at that time.

**Comment by jcfranco** [comment] 2024-07-19 18:57
I like the proposal for `inactive`. ✨🏆✨

Would it be possible to style slightly different from disabled to avoid confusion? That'd be my only concern.

**Comment by geospatialem** [comment] 2024-09-17 19:58
Thanks all for the great discussions and insights to use cases. 

Calcite is proceeding with the above request on `list-item` via a new boolean property, `unavailable`, anticipated implementation of Q4 2024 (25.R1).

**Comment by geospatialem** [comment] 2024-09-26 14:39
Verified with Chromatic build with `list-item`'s new `unavailable` attr/prop:

![verify-5664](https://github.com/user-attachments/assets/573075f9-a827-4f47-9e6c-bc39dcbf6c04)

**Closed by geospatialem** 2024-09-26 14:39 UTC
Labels: enhancement, convention, 5 - verified, p - medium, figma changes, ArcGIS Field Apps, ArcGIS Map Viewer, estimate - 5, ArcGIS Web Analysis, c-calcite-list-item
