### ISSUE TITLE
[Tile Select] Tile Select React components do not correctly display radio buttons / allow selection

### ISSUE THREAD

**Issue by pllcoster** [Esri/calcite-design-system#8495] opened 2023-12-23 01:06 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using Calcite React components after upgrading to 2.1.0,  a Tile Select component with either no `type` property or `type="radio"`, no radio button appears and the tiles are not selectable.

![image](https://github.com/Esri/calcite-design-system/assets/146282673/3a61472a-8a3b-4b0d-9ddb-0ba5944f92f8)

### Expected Behavior

Expect Radio buttons to appear as default or if type is set to "radio"

Correct functionality with calcite 1.9.1 can be seen here:
https://codesandbox.io/p/sandbox/calcite-1-9-1-tile-select-zdt9t7?file=%2Fsrc%2FApp.js%3A22%2C49

### Reproduction Sample

https://codesandbox.io/p/sandbox/caclite-2-1-0-tile-select-wx4tzr?file=%2Fsrc%2FApp.js%3A22%2C49

### Reproduction Steps

Create CalciteTileSelect components as described above, with type set to radio or left as default. Note that in the code sandbox checkboxes also appear to be broken.

### Reproduction Version

2.1.0

### Relevant Info

calcite-components-react

### Regression?

Worked in 1.9

### Priority impact

p2 - want for current milestone

### Impact

We wish to use the tile component as a radio button in our app. With this broken we may have to swap to a different component to have a similar selection experience.

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Knowledge

**Comment by pllcoster** [comment] 2023-12-23 01:38
From the discussion:

Your comment pointed me in the right direction - it seems like previously we did not have to separately import `@esri/calcite-components/dist/components/calcite-radio-button` to have the radio button working in the tile select - but if I add this import after updating to 2.1.0, the radio buttons come back on the tile select element

**Comment by geospatialem** [comment] 2024-01-11 20:12
Spike to investigate if the component could automatically import components, possibly similar to `modal`.

**Comment by jcfranco** [comment] 2024-01-25 23:35
It looks like dynamic tags passed to `document.createElement` prevent the Stencil build from auto-defining them. Fortunately, the fix for this is simple and is feasible for the current release.

**Comment by eriklharper** [comment] 2024-01-26 17:49
Nice sleuthing on this @jcfranco ! 😉

**Comment by jcfranco** [comment] 2024-01-26 23:05
@DitwanP @geospatialem `combobox` was technically also fixed although the issue isn't likely to show up because we expect it to be used with `combobox-item`s.

**Comment by DitwanP** [comment] 2024-01-31 21:51
🍭 Verified on `2.4.0-next.1`

**Closed by DitwanP** 2024-01-31 21:51 UTC
Labels: bug, 3 - installed, p2 - want for current milestone, ArcGIS Knowledge, calcite-components-react, spike complete
