### ISSUE TITLE
Shared Close Button mixin

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8925] opened 2024-03-11 17:56 UTC
### Description

A lot of components implement a close button. This is a common UI pattern who's user experience and micro interactions should not change across components. 

Suggestion. Create a functional mixin similar to the floating panel which allows for style customizations.

### Proposed Advantages

Single source of truth for close button interactions and styles.

### Which Component

alert, chip, modal, notice, popover, tab-title, combobox, ... others

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment] 2024-03-14 19:30
This looks like a duplicate of https://github.com/Esri/calcite-design-system/issues/6640.

**Closed** 2024-03-18 15:55 UTC
Labels: refactor, 0 - new, needs triage, calcite-components
