### ISSUE TITLE
Error using calcite components in Gatsby site during server-side rendering

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-design-system#7493] opened 2023-08-09 01:14 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using calcite components 1.5.X  on a page in a Gatsby site, the page throws an error during server-side rendering `error "navigator" is not available during Server-Side Rendering`.  The stack trace takes me to the interactive.ts file where it is using `navigator` to check the user agent string: https://github.com/Esri/calcite-design-system/blob/bb07831eb518d1d617b765e1f14279480c6051fc/packages/calcite-components/src/utils/interactive.ts#L30-L36

### Expected Behavior

I would expect a server-side rendered page in a Gatsby site (or other static site generator) to be able to render the components without throwing a build error.

### Reproduction Sample

See devtopia documentation repo

### Reproduction Steps

1. Go to the documentation repo and check out the branch `kit12303/update-150`
2. Run `npm run build:afd`
3. After the build gets to the HTML rendering step, it will throw an error.

### Reproduction Version

1.5.1

### Regression?

1.4.3

### Priority impact

p1 - need for current milestone

### Impact

Blocks the developer documentation from being deployed for the 1.5 release.

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Developer Experience

**Comment by jcfranco** [comment] 2023-08-15 01:21
After some additional research, I think the crux of this makes it a duplicate of #7486.

The commit that caused the Gatsby SSR build to start failing was 1.5.0-next.9. From the [range of commits between 1.5.0-next.8 and 1.5.0-next.9](https://github.com/Esri/calcite-design-system/compare/@esri/calcite-components-react@1.5.0-next.8...@esri/calcite-components-react@1.5.0-next.9), the change to enable `includeImportCustomElements` seemed like the most likely culprit. Thanks to @benelan's sleuthing, he confirmed that that feature was adding static imports from the `components` (where Stencil's `isBrowser` build flag is always true) output target to be pulled in early in the build process and causing errors about accessing client APIs that aren't available during SSR.

**Comment by geospatialem** [comment] 2023-08-15 23:35
Verified in `1.6.0` with the documentation repo's `kit12303/test` branch at commit `c60a528c0cd56818349301e4a6042f0871260621`, only modifying the CC and CCR versions.

**Closed by geospatialem** 2023-08-15 23:35 UTC
Labels: bug, p - high, 4 - verified, ArcGIS Developer Experience, estimate - 1, p1 - need for current milestone, calcite-components-react, calcite-components
