### ISSUE TITLE
[input-time-zone] Improve the way input time zone picker offset mode handles daylight saving

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-design-system#8715] opened 2024-02-09 04:00 UTC
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Improve the way that input time zone picker offset mode handles daylight saving
<img width="1689" alt="image" src="https://github.com/Esri/calcite-design-system/assets/26078106/93a7a588-154e-4d03-aa53-aa5a16b2695e">

### Acceptance Criteria

NA

### Which Component

calcite-input-time-zone

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Survey123

**Comment by jcfranco** [comment] 2024-03-06 20:37
@fendiaoxiaoshuazi Thanks for submitting this. Can you provide a bit more context behind those screenshots? Is the component being used at different points in time? Are you using `referenceDate` to modify the generated time zone options?

**Comment by fendiaoxiaoshuazi** [comment] 2024-03-12 02:23
Sorry I should add more information to the issue description. I create the screenshot by switching the date of my device. The left side is the time picker during daylight saving time, while the right is during standard time. It seems like different sets of cities appear for different times, for example, Los Angeles only appears on the time zone picker during standard time.

**Comment by jcfranco** [comment] 2024-04-18 16:11
@fendiaoxiaoshuazi Thanks for info. If you are not using `referenceDate` and the dates between devices affects DST, I believe what you are observing is by design. Time zones in offset mode are grouped together if they:

* share same time/date
* are on the same continent
* share DST support

Grouping uses the current date by default unless `referenceDate` is specified.

**Comment by jcfranco** [comment] 2024-05-22 22:57
Closing per ☝️.

**Closed by jcfranco** 2024-05-22 22:57 UTC
Labels: enhancement, 0 - new, needs triage, need more info, ArcGIS Survey123, impact - p3 - not time sensitive
