### ISSUE TITLE
Color Picker's alpha-channel slider scope doesn't update

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7761] opened 2023-09-18 20:18 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using the alpha-channel slider, the scope doesn't update to reflect the current opacity.
![CleanShot 2023-09-18 at 13 10 09](https://github.com/Esri/calcite-design-system/assets/108549080/bb54ec3c-5593-4e87-9e94-f6a8e2561b38)

### Expected Behavior

I would expect the color in the scope to change.
![image](https://github.com/Esri/calcite-design-system/assets/108549080/61a4bbba-7093-4273-822a-20f219a1d8c6)

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/color-picker/

### Reproduction Steps

1. Enable alpha-channel
2. Use alpha-channel slider

### Reproduction Version

v1.8.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by ashetland** [comment] 2024-02-08 23:43
Hey team, I think I expected the color in the alpha channel scope to fade out to white like pictured above instead of being completely transparent.

**Comment by geospatialem** [comment] 2024-02-13 16:12
> Hey team, I think I expected the color in the alpha channel scope to fade out to white like pictured above instead of being completely transparent.

@Elijbet - can you confirm on @ashetland's comment above? It looks like the scope (where the pointer is the below screenshot) differs from the expected behavior.

### Expected
![image](https://github.com/Esri/calcite-design-system/assets/5023024/b4db12a9-9dfa-41c7-abf2-126a7fdc6b7f)

### With `2.5.0-next.2`
![image](https://github.com/Esri/calcite-design-system/assets/5023024/f08d5587-090b-458b-a563-15620f7c6411)

**Comment by jcfranco** [comment] 2024-02-14 18:52
@ashetland @geospatialem IMO, the current behavior is expected since the checkerboard pattern is being used to represent full transparency.

This is common in other color picker components:

https://uiwjs.github.io/react-color/
https://jscolor.com/
https://opensource.adobe.com/spectrum-web-components/components/color-area/ 👇
<img width="532" alt="Screenshot 2024-02-14 at 10 44 55 AM" src="https://github.com/Esri/calcite-design-system/assets/197440/98c8ccf6-c188-466e-9ecb-dd2da7a67fcc">

**Comment by ashetland** [comment] 2024-02-14 19:02
Yeah definitely see this both out in the wild. Even your first [example](https://uiwjs.github.io/react-color/) shows both approaches next to each other😆. If the current setup feels more Calcite-y, then happy to go with this and update in the future if folks voice opinions.

**Comment by geospatialem** [comment] 2024-02-14 21:35
Marking as verified per on the conversation above in https://github.com/Esri/calcite-design-system/issues/7761#issuecomment-1944409876 and https://github.com/Esri/calcite-design-system/issues/7761#issuecomment-1944425756.

**Closed by geospatialem** 2024-02-14 21:35 UTC
Labels: bug, p - low, 4 - verified, Calcite (design), estimate - 3, p3 - want for upcoming milestone, calcite-components, visual changes
