### ISSUE TITLE
Allow calcite-list to search without the search box

### ISSUE THREAD

**Issue by fangqidev** [Esri/calcite-design-system#10257] opened 2024-09-10 06:15 UTC
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

We want to use a single search box for multiple calcite-list-based widgets at the same time in the ExB. Right now, the calcite list is only able to filter items with a search box (by setting `visibleItems.filter` to `true` in the JS API).

### Acceptance Criteria

An option to hide the search input box when `filter` is `true` and the items number exceeds `minFilterItems`. So we can use a single self-implemented search input box for several calcite lists at the same time. For example, we can apply the same search content for a layerlist, a tablelist and a basemaplist.

### Relevant Info

JSAPI issue: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/64561
ExB issue: https://devtopia.esri.com/Beijing-R-D-Center/ExperienceBuilder-Web-Extensions/issues/21467#issuecomment-4979724

### Which Component

calcite list

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Experience Builder

**Comment by geospatialem** [comment] 2024-09-10 11:47
duplicate of #10258, closing the above.

**Closed by geospatialem** 2024-09-10 11:47 UTC
Labels: enhancement, 0 - new, needs triage, ArcGIS Experience Builder, impact - p2 - want for an upcoming milestone
