### ISSUE TITLE
split accordion-item header and content padding

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#10762] opened 2024-11-18 18:39 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

https://github.com/Esri/calcite-design-system/pull/10721#pullrequestreview-2437271640

The current design pattern for accordion item is to have content and heading padding size in unison.

### Acceptance Criteria

The proposed design pattern is accordion item heading and content padding size separately.

### Which Component

accordion-item

### Example Use Case

As a developer I want the padding of the accordion-item heading to be 10px and the content padding to be 0px.

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment] 2024-11-21 23:14
@alisonailea Can you update the labels for verification? I've added in the labels and express triaged the above to November/current milestone.

**Comment by DitwanP** [comment] 2024-11-22 18:38
@alisonailea I think the padding token is still applying to both heading and content, but maybe I'm missing something.

Accordion demo page with `calcite-accordion-item { --calcite-accordion-item-content-space: 40px; }`:
https://github.com/user-attachments/assets/9aaea4fd-2668-42c1-8ac1-97826d5355bb

**Comment by geospatialem** [comment] 2024-12-12 19:15
@alisonailea It looks like the PR has been merged, is this issue ready for verification? If so, can you add the `3 - installed` label for us? 🤜🏻 🤛🏻

**Comment by DitwanP** [comment] 2024-12-16 23:48
Verified locally on `dev` the `--calcite-accordion-item-content-space` token is now only applying to the content as intended.

**Closed by DitwanP** 2024-12-16 23:48 UTC
Labels: enhancement, p - high, 3 - installed, Calcite (design), estimate - 2, impact - p3 - not time sensitive, calcite-components, calcite-design-tokens
