### ISSUE TITLE
List item: slotted actions obstruct portion of list outline with active

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#7538] opened 2023-08-16 18:44 UTC
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

1.4.3 and higher:

![image](https://github.com/Esri/calcite-design-system/assets/14297903/4432a429-96aa-4d2a-bd3a-c69bc9e274ba)

### Expected Behavior

1.4.2:

![image](https://github.com/Esri/calcite-design-system/assets/14297903/1a50f08a-ee75-4331-a21b-dbdb72bb2005)

### Reproduction Sample

https://codepen.io/geospatialem/pen/VwOXGgr
https://codepen.io/COV-GIS/pen/wvRwmPV?editors=100

### Reproduction Steps

Switch between 1.4.2 and 1.4.3 in sample.

### Reproduction Version

1.6.0

### Regression?

1.4.2

### Priority impact

impact - p3 - not time sensitive

### Impact

Does not affect usability or workflows. Just aesthetics.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by jcfranco** [comment] 2023-08-18 21:02
As a workaround, action's `appearance` prop can be set to `transparent` (via @driskull 🏆). cc @macandcheese

**Comment by geospatialem** [comment] 2023-08-30 15:08
Additional information needs to determine a potential fix that doesn't impact the original fix creating the regression.

**Comment by geospatialem** [comment] 2023-10-30 14:34
A spike will be conducted before the end of 2023 to determine:
1. A solution between the current bug and the previous border issue
    - Issue: https://github.com/Esri/calcite-design-system/issues/6373
    - Commit: https://github.com/Esri/calcite-design-system/commit/a810943fdea2c1f90f5deca35ab0501287e45489
2. Should we consider moving the DOM in `list` with `filter`? (this might be risky change, should we pursue it?)
3. Are there other alternatives we should consider?

cc @macandcheese

**Comment by geospatialem** [comment] 2023-11-22 15:58
Spike effort to determine next steps - refer to https://github.com/Esri/calcite-design-system/issues/7538#issuecomment-1785350627 for additional context cc @macandcheese @brittneytewks

**Comment by josercarcamo** [comment] 2024-05-16 18:39
Met with @driskull. There is probably nothing that can be done because the slotted action has a higher z-index than the td. @jcfranco may be we can discuss further.

**Comment by driskull** [comment] 2024-05-16 18:41
@jcfranco I don't think theres any way to "fix" this. I think the workaround you specified is the correct way to go about this. 

The only thing we could do is change the focus outline offset here https://github.com/Esri/calcite-design-system/blob/4be8254092e84b8e58df2eb7c5f06ac77d5ef3e2/packages/calcite-components/src/components/list-item/list-item.scss#L87-L90

**Comment by josercarcamo** [comment] 2024-05-23 23:13
If we use a border instead of outline, it works:

![image](https://github.com/Esri/calcite-design-system/assets/138070439/f39f8c28-035b-4277-a2ca-446069ffd7c6)

**Comment by josercarcamo** [comment] 2024-05-23 23:16
If we use a border instead of outline, it works:

![image](https://github.com/Esri/calcite-design-system/assets/138070439/4666a430-9cd7-4a15-845f-17c9f064bea3)
 
So instead of:

`@apply focust-inset`

It would have to be some border:

`border: 2px solid blue;`

**Comment by driskull** [comment] 2024-05-23 23:28
I think we should continue to use an outline as it's the appropriate CSS statement for focused elements.

If we just remove the inset rule does it fix it?

**Comment by josercarcamo** [comment] 2024-06-05 22:30
@driskull no, it doesn't fix it by removing the inset rule.

**Comment by driskull** [comment] 2024-06-05 23:08
@josercarcamo are you sure? If I try to do it in the browser it seems to work:

![Jun-05-2024 15-57-25](https://github.com/Esri/calcite-design-system/assets/1231455/248c14a7-d07a-4bf1-a06b-5414457299d4)

**Comment by alisonailea** [comment] 2024-06-05 23:19
> I think we should continue to use an outline as it's the appropriate CSS statement for focused elements.

The outline property was chosen as the browser default visual indicator of a focus state so that it wouldn't interfere with custom CSS border styles. In this case we are already adding custom styles for both the border color and outline and setting a border here for focus styles will not override other custom border styles. AAA accessibility requirements only stipulate 

* is at least as large as the area of a 2 [CSS pixel](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance#dfn-css-pixel) thick [perimeter](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance#dfn-perimeter) of the unfocused component or sub-component, and
* has a contrast ratio of at least 3:1 between the same pixels in the focused and unfocused states.

User experience is also not effected by this solution.

**Comment by josercarcamo** [comment] 2024-06-06 00:09
@driskull it almost works, but not quite:

![image](https://github.com/Esri/calcite-design-system/assets/138070439/1e040742-67ab-4ae8-a2f6-5647a68f820a)

**Comment by driskull** [comment] 2024-06-06 15:58
ah, dang. Ok. Its a little better though.

**Comment by macandcheese** [comment] 2024-06-21 17:51
For verification - I think the installed PR still has some issues to resolve - it is causing overlaps as the focus is outset and ends up not being visible in Panel, etc:

Merged PR: 
<img width="972" alt="Screenshot 2024-06-21 at 10 50 27 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/c24e7fed-53b7-4d6a-b8d4-90122d527570">

<img width="699" alt="Screenshot 2024-06-21 at 10 33 25 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/777ace76-5199-42c3-b497-518ee38ea159">



Expected (https://github.com/Esri/calcite-design-system/pull/9534):
<img width="699" alt="Screenshot 2024-06-21 at 10 34 18 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/21e08a17-ad09-43f1-814a-7b74a3f27434">

<img width="699" alt="Screenshot 2024-06-21 at 10 34 03 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/2200f32d-45e7-40d0-a874-6d7f06157b2d">

**Comment by DitwanP** [comment] 2024-06-21 18:15
Confirming what Adam said above.![image](https://github.com/Esri/calcite-design-system/assets/60022782/ce177506-2cd5-4ec5-887e-57fcda525ce4)

Reassigning to remedy this 👆

**Comment by DitwanP** [comment] 2024-06-24 23:34
This looks good to me locally on `dev` 

PREVIOUSLY:
![image](https://github.com/Esri/calcite-design-system/assets/60022782/3b54adfa-2b95-4d58-86be-ee5fb6368950)
![image](https://github.com/Esri/calcite-design-system/assets/60022782/293b86db-8934-4691-873e-c79e0ae4bb0f)

CURRENTLY:
![image](https://github.com/Esri/calcite-design-system/assets/60022782/b0ea331e-4065-408c-b6cc-d4a0efe6f379)![image](https://github.com/Esri/calcite-design-system/assets/60022782/bfec283a-7a1e-4a82-af31-6754a6e5d85e)

@macandcheese thoughts?

**Comment by DitwanP** [comment] 2024-06-24 23:39
🍡 Verified

**Closed by DitwanP** 2024-06-24 23:39 UTC
Labels: bug, 3 - installed, p - medium, regression, has workaround, impact - p3 - not time sensitive, calcite-components, spike, c-list
