### ISSUE TITLE
Dropdown item does not support "disabled" in React

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-design-system#7393] opened 2023-07-31 14:28 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The Dropdown item component does not support the "disabled" property, and it would be nice if it did.  Sometimes our design calls for dropdown item options to be conditionally not allowed

### Acceptance Criteria

Dropdown item can be disabled which apply a "greyed out" styling, disable the click/selection handler, and change the hover behavior similar to other disabled elements

### Which Component

DropdownItem

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Knowledge

**Comment by geospatialem** [comment] 2023-07-31 14:35
@RSantosGIS Thanks for the request! It looks like a duplicate of #6667, as this is functionality not supported outside of React as well. Added the `ArcGIS Knowledge` label for additional context. The issue is currently targeted for October.

**Closed by geospatialem** 2023-07-31 14:35 UTC
Labels: enhancement, 0 - new, needs triage, p4 - not time sensitive, ArcGIS Knowledge, calcite-components-react

**Comment by RSantosGIS** [comment] 2023-07-31 14:37
@geospatialem ok awesome!  Sorry about that, I promise I did search for something first!

**Comment by geospatialem** [comment] 2023-07-31 14:42
No worries at all, appreciate the request! ✨
