### ISSUE TITLE
Calcite-Modal "Close" Button not Triggering calciteModalClose event

### ISSUE THREAD

**Issue by tom12993** [Esri/calcite-design-system#7655] opened 2023-09-01 18:58 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

In `calcite-modal` when using the built-in "Close" button in the header, the `calciteModalClose` and `calciteModalBeforeClose` events aren't firing.

### Expected Behavior

Using the "Close" button should trigger the `calciteModalClose` event.

### Reproduction Sample

https://codepen.io/tom12993/pen/MWZePrK?editors=1001

### Reproduction Steps

1. Go to provided [codepen link](https://codepen.io/tom12993/pen/MWZePrK?editors=1001)
2. Observe that the Calcite version is set to `1.7.0`
3. Use the "Open modal" button to open the calcite-modal
4. Use the "Cancel" button to close the calcite-modal
  a. Observe the Console, and see that the event is logged
5. Use the "Open modal" button again to open the calcite-modal
6. Use the "X" button in the header to close the calcite-modal
  a. Observe the Console, and see that the event is NOT logged
7. Repeat in `1.6.1` and notice that the event is triggered both times.

### Reproduction Version

1.7.0

### Regression?

1.6.1

### Priority impact

p0 - emergency

### Impact

Modals aren't working as expected when closed via the "X" button. Prevents the modal from being opened a 2nd time in our case, because the modal's "open" state is never set to false due to the event not triggering. Also affects our behaviors that are expected to happen when our modals close.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Monitor

**Comment by jcfranco** [comment] 2023-09-01 19:10
@driskull Do you think you could look at this one? Possibly caused by https://github.com/Esri/calcite-design-system/pull/7470.

**Comment by geospatialem** [comment] 2023-09-01 23:47
This also seems to be occurring with `sheet`'s `calciteSheetClose` event: https://codepen.io/geospatialem/pen/jOXrXQQ

**Comment by driskull** [comment] 2023-09-05 16:01
@jcfranco I think the `openCloseComponent` will need to be updated to account for `opened` being the source of truth for some components. Do you want me to take that or @Elijbet?

**Comment by jcfranco** [comment] 2023-09-05 19:21
Excellent sleuthing! 🕵️ 

Assigning to you for the moment since you're already taking a look. @Elijbet or myself can help out if needed.

**Comment by geospatialem** [comment] 2023-09-06 20:16
Verified on `main` when the `modal` is closed via the scrim click, `Esc` key, and component's close button.

**Closed by geospatialem** 2023-09-06 20:16 UTC
Labels: bug, p - high, 4 - verified, regression, ArcGIS Monitor, p0 - emergency, calcite-components
