### ISSUE TITLE
[Action] - Active syles are not present on actions with transparent appearance

### ISSUE THREAD

**Issue by sagewall** [Esri/calcite-design-system#10982] opened 2024-12-04 20:30 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Beginning with version `2.12.0-next.31` and currently at `2.13.2` there is no visible change to the action when setting the active property on an action element if the appearance is set to transparent.  Both actions in this screenshot are identical with the exception of the second action has `appearance="transparent"`
![image](https://github.com/user-attachments/assets/9a99e6d9-6517-4a95-9f2d-be206b83fd11)

### Expected Behavior

Visually be able to determine which actions are visible regardless of the `appearance` attribute value as before the regression took place.
![image](https://github.com/user-attachments/assets/1c572d46-a05d-4b04-8034-2c2f3d131c4b)

### Reproduction Sample

https://codepen.io/sagewall/pen/JoPGPwJ

### Reproduction Steps

1. Open this [code pen](https://codepen.io/sagewall/pen/JoPGPwJ)
2. Observe how the transparent action has no styling to indicate it's active

### Reproduction Version

2.13.2

### Relevant Info

Seems independent of hardware

### Regression?

2.12.0-next.31

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

Impacts users ability to see active actions in several JS SDK widgets and components

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment] 2024-12-04 20:46
Regression related to #10058, refer to Matt's comment for more specifics: https://github.com/Esri/calcite-design-system/pull/10058#discussion_r1869973822

**Comment by geospatialem** [comment] 2024-12-12 19:11
@alisonailea It looks like the PR has been merged, is this issue ready for verification? If so, can you add the `3- installed` label for us? 🤜🏻 🤛🏻

**Comment by geospatialem** [comment] 2024-12-16 17:50
The above doesn't seem to be mitigated with the original repro case in the latest `3.0.0-next.65`. 

@alisonailea can you take a peek to explore what might be occurring?: https://codepen.io/geospatialem/pen/azopwzM 👀

**Comment by geospatialem** [comment] 2024-12-16 20:16
@alisonailea To mitigate the regression we should migrate to `transparent.hover`, here's a before an after the change for comparison:

| Before | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/4f0b091f-796c-42fd-8def-d803e2f74a61) | ![image](https://github.com/user-attachments/assets/0e8d743d-eb4e-41aa-8237-72de98d4fd21) |

**Comment by geospatialem** [comment] 2024-12-16 23:59
Verified on `3.0.0-next.68` 🎉

**Closed by geospatialem** 2024-12-16 23:59 UTC
Labels: bug, p - high, 4 - verified, regression, ArcGIS Maps SDK for JavaScript, estimate - 2, impact - p2 - want for an upcoming milestone, calcite-components
