### ISSUE TITLE
Nested combobox groups disappear after selection

### ISSUE THREAD

**Issue by tom7248** [Esri/calcite-design-system#8727] opened 2024-02-12 14:06 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If a `calcite-combobox` has two or more levels of `calcite-combobox-item-group`s that only contain other `calcite-combobox-item-group`s, and `calcite-combobox-item`s at the bottom of the hierarchy, when one of those items is selected, the group hierarchy is removed from the combobox dropdown. 

### Expected Behavior

The combox content should not change with selection

### Reproduction Sample

https://codepen.io/_t_o_m_/pen/LYagJmY

### Reproduction Steps

1. Click in the combox to display the dropdown
2. Select "Item 1.1.1", the item in the group hierarchy with only groups
3. Click in the combobox again to display the dropdown
4. The group hierarchy that contains "Item 1.1.1" no longer displays

### Reproduction Version

2.4.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by bedzhist** [comment] 2024-06-02 12:01
I guess the bug is caused by this function (packages/calcite-components/src/components/combobox/utils.ts):

![image](https://github.com/Esri/calcite-design-system/assets/137164516/953f770e-4bcf-4133-8f7a-8a4f49948a2e)

It should be updated to something like this:
```
export function getAncestors(element) {
  const ancestors = [];
  let currentElement = element.parentElement?.closest(ComboboxChildSelector);
  while (parent) {
    ancestors.push(parent);
    currentElement = parent.parentElement?.closest(ComboboxChildSelector);
  }
  return ancestors;
}
```

**Comment by jcfranco** [comment] 2024-06-24 18:54
The original issue was fixed by https://github.com/Esri/calcite-design-system/issues/7212 (see [updated repro case](https://codepen.io/jcfranco/pen/qBGKNWY)).

**Comment by DitwanP** [comment] 2024-06-24 22:07
🍡 Verified locally on `dev`

**Closed by DitwanP** 2024-06-24 22:07 UTC
Labels: bug, p - low, 3 - installed, ArcGIS Field Apps, estimate - 5, impact - p3 - not time sensitive, calcite-components
