### ISSUE TITLE
Allow setting the input-time-picker value from a ISO 8601 formatted value or a Date instance

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#4277] opened 2022-03-19 00:46 UTC
### Description

Currently, it's a bit challenging to set the time picker value from an incoming Date instance. End users need to build a string from the date instance and use that to set the value. Allowing users to set the time via a ISO 8601 formatted value or a Date instance would be a great improvement.

### Acceptance Criteria

Similar to `input-date-picker` and `date-picker` users should be able to

1. set `value` to an ISO 8601 formatted string
2. set `valueAsDate` (**new**) to a `Date` instance

If time permits, it'd be great to have 1. handle values similar to what [Luxon accepts](https://moment.github.io/luxon/#/parsing?id=iso-8601). Otherwise, this can be tackled as a separate issue.

### Which Component

* `input-time-picker`
* `time-picker`

### Example Use Case

https://codepen.io/jcfranco/pen/mdpPwdj?editors=1010

**Comment by jcfranco** [comment] 2024-10-21 19:25
Related: #8578

**Comment by geospatialem** [comment] 2024-10-21 20:44
Closing in favor of the duplicate of the issues mentioned in Franco's comment above https://github.com/Esri/calcite-design-system/issues/4277#issuecomment-2427539639.

**Closed by geospatialem** 2024-10-21 20:44 UTC
Labels: enhancement, p - low, 0 - new, i18n-l10n, estimate - 5
