### ISSUE TITLE
calcite-action-group - Actions are cut off in Safari when action group has fixed overlay positioning in a panel

### ISSUE THREAD

**Issue by lboyd93** [Esri/calcite-design-system#8028] opened 2023-10-18 18:54 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

In Safari, the grouped actions in the drop down are cut off when expanded.
![2023-10-18_11-22-39](https://github.com/Esri/calcite-design-system/assets/22916889/07d043ad-161a-4308-b708-c807c216fdeb)

### Expected Behavior

The grouped actions should not be cut off, but they should overlay the rest of the calcite panel. This is the behavior in Chrome and Firefox.
![2023-10-18_11-22-55](https://github.com/Esri/calcite-design-system/assets/22916889/bb1429ae-0f7c-4e0f-9325-afa012a5d035)

### Reproduction Sample

https://codepen.io/driskull/pen/MWZNOMR?editors=1000

### Reproduction Steps

1. Open sample in Safari: https://codepen.io/driskull/pen/MWZNOMR?editors=1000
2. Select the grouped actions drop down. Note it only shows four actions and it's all within the panel.
3. Open the sample in chrome and repeat step 2. Note all the actions are shown and it overlaps the panel.

### Reproduction Version

1.9.2

### Relevant Info

macOS 13.6 (22G120)
Safari Version 17.0 (18616.1.27.111.22, 18616)

### Priority impact

p2 - want for current milestone

### Impact

This issue impacts the ArcGIS Online Map Viewer and custom ArcGIS Maps SDK for JavaScript applications used in Safari that utilize popups with many actions. The actions listed at the end of the group will be unusable.

cc @driskull

Example of JS SDK application: https://codepen.io/laurenb14/pen/bGOXayX?editors=1000

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment] 2023-10-18 20:32
This one looks like a Maps SDK issue. I think we can close it.

**Comment by driskull** [comment] 2023-10-18 21:18
Reopening, seems like it does happen in safari within a flow/panel

**Comment by asangma** [comment] 2023-10-24 23:42
I've done some testing.
It seems like it may be coming from the overflow: hidden rule in [CalcitePanel](https://github.com/Esri/calcite-design-system/blob/anveshmekala/2162-combobox-clear-user-input-on-blur/packages/calcite-components/src/components/panel/panel.scss#L12).

I have a Codepen in which I turn off the `overflow: hidden` on Panel and it seems to work.
I'm not sure if it breaks other stuff though.

https://codepen.io/mtb-alan/pen/poGJJaM?editors=0100

**Comment by DitwanP** [comment] 2023-11-20 19:52
Verified on Safari
<img width="618" alt="Screenshot 2023-11-20 at 11 35 44 AM" src="https://github.com/Esri/calcite-design-system/assets/60022782/81ccf8f9-ea78-4d24-898c-e5af020a55e0">

**Comment by geospatialem** [comment] 2024-02-15 15:28
Reopening from the revert above https://github.com/Esri/calcite-design-system/issues/8028#ref-pullrequest-2126306731

**Comment by jcfranco** [comment] 2024-02-29 22:22
Confirmed this is still an issue with the latest: https://codepen.io/jcfranco/pen/rNbNKgx?editors=1000.

[Here](https://github.com/Esri/calcite-design-system/pull/8711#issuecomment-1942858596) are Matt's findings from the revert PR. 🕵️

**Comment by DitwanP** [comment] 2024-06-12 18:35
🍯 Verified locally on `dev` 

Screenshot:
(Safari - Version 17.5)
![image](https://github.com/Esri/calcite-design-system/assets/60022782/cf78ea9f-aafe-4111-abeb-da14417fe13b)

**Closed by DitwanP** 2024-06-12 18:35 UTC
Labels: bug, browser-safari, 3 - installed, p - medium, ArcGIS Maps SDK for JavaScript, impact - p2 - want for an upcoming milestone, calcite-components, spike
