### ISSUE TITLE
Crashes on Node.js due to lack of `exports` map in `package.json`

### ISSUE THREAD

**Issue by benmccann** [Esri/calcite-design-system#5077] opened 2022-08-03 15:39 UTC
### Actual Behavior

Crashes when running in Node.js without a bundler

The simplest fix and best is to add an `exports` map in `package.json`. Alternatively, all packages referring to this one could be updated to do CommonJS-style imports (i.e. `import * as components from '@arcgis/calcite-components'`)

This has been reported as an issue in multiple places:
- https://github.com/sveltejs/kit/issues/5800
- https://github.com/sveltejs/kit/discussions/5274
- https://community.esri.com/t5/arcgis-api-for-javascript-questions/svelte-kit-build-error/m-p/1123928

This also affects other packages such as `@esri/calcite-colors`

### Expected Behavior

Package loads and runs

### Reproduction Sample

https://github.com/georgeboot/svelte-kit-named-export-issue

### Reproduction Steps

```
git clone git@github.com:georgeboot/svelte-kit-named-export-issue.git
cd svelte-kit-named-export-issue
npm install
npm run dev
```
Visit http://localhost:5173/arcgis to see the error

### Reproduction Version

1.0.0-beta.82

### Relevant Info

```
Named export 'setAssetPath' not found. The requested module '@esri/calcite-components/dist/components/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@esri/calcite-components/dist/components/index.js';
const {setAssetPath: o}from"@esri/calcite-components/dist/components/index.js";import{getAssetUrl: s}from"../../assets.js";import"../../core/has.js";import{makeAbsolute: t}from"../../core/urlUtils.js";let e;function r(){o(t(s(e)))}e="components/assets";export{r: commitAssetPath} = pkg;
```

**Comment by tcc-sejohnson** [comment] 2022-08-03 15:43
Just copying the repro from one of our issues to make it easier on the lib authors. 

1. Clone the following repo: https://github.com/georgeboot/svelte-kit-named-export-issue
2. Run npm install
3. Run npm run dev
4. Visit http://localhost:5173/arcgis
5. See error

**Comment by benmccann** [comment] 2022-08-03 16:11
> A [codepen](https://codepen.io/pen?template=RwgrjEx), [codesandbox](https://codesandbox.io/s/calcite-template-p95kp?file=/src/App.js), or [jsbin](https://jsbin.com/wiguxohisa/edit?html,output) that reproduces the issue.

None of those would work, because they only run the JS in the browser and this is a Node.js issue. I could provide a stackblitz that reproduces the issue, but don't really see the point since I've already provided a github repository

@Elijbet @jcfranco could we get the `incomplete issue report` label removed since the bot incorrectly applied it?

**Comment by benelan** [comment] 2022-08-03 17:03
It's removed, sorry about that!

**Comment by samMatenaer** [comment] 2022-08-09 17:49
We're also running into this issue using Vitest in our project

**Comment by benelan** [comment] 2022-08-15 23:41
The GeoNet forum that you linked has the correct answer; you will need to use dynamic imports. Here is a SvelteKit example using the ArcGIS API for JavaScript:
https://github.com/benelan/arcgis-esm-samples/tree/main/jsapi-sveltekit-template

Does that help? If not can you please elaborate on the issue you are facing and/or provide another repro sample that better demonstrates the problem? Thanks!

**Comment by benmccann** [comment] 2022-08-15 23:48
This issue is asking for `exports` to be added to the `package.json` so that users are no longer forced to use dynamic imports, but can use regular static imports

**Comment by benelan** [comment] 2022-08-16 00:01
I'm not very familiar with SvelteKit, but wouldn't static imports cause the ArcGIS JavaScript API to render on the server? They don't support server side rendering, so even if we add `exports` the reproduction sample will not work.

**Comment by benmccann** [comment] 2022-08-16 02:59
Yes, it would cause it to render on the server. I had assumed these components would work on the server because you distribute CommonJS files. I'm a maintainer of SvelteKit and haven't used these components myself, but wanted to get to the bottom of this as we've seen users running into it. What scenario are the CommonJS files intended for if not for running on the server? It could make sense to remove the CommonJS files and add `"type": "module"` to the `package.json` if these are only intended to run in the browser.

**Comment by benelan** [comment] 2022-08-16 19:00
Sorry if I wasn't clear, I was saying that the ArcGIS API for JavaScript ([`@arcgis/core`](https://www.npmjs.com/package/@arcgis/core)) cannot render on the server. So the repro app won't work even after fixing the errors from this issue, you will still need to use dynamic imports.

Putting the repro sample aside, Calcite Components are web components and they rely on browser APIs. So using static imports won't work, you will need to use the [`hydrate`](https://stenciljs.com/docs/hydrate-app) build. Here is some more documentation about [why CommonJS modules are provided](https://stenciljs.com/docs/module-bundling#commonjs-dependencies). I'll fix the Calcite Component specific errors but it won't fix any of the problems you are facing.

**Comment by benmccann** [comment] 2022-08-16 20:27
I'm not following the explanation for why CommonJS modules are provided. That link just says you have to use `rollup-plugin-commonjs` if you're using Rollup and encounter a CommonJS dependency. But that's not really a reason to make dependencies be CommonJS in the first place. Rollup users would much prefer if you didn't make them utilize `rollup-plugin-commonjs` to handle a given component

**Comment by benelan** [comment] 2022-08-16 21:11
Sorry my thoughts got shmushed together. I meant:

> Here is an [example using CommonJS](https://github.com/benelan/calcite-samples/blob/master/ssr-frameworks/next/server.js#L1). Here is some documentation about [how I can fix the Calcite Components errors](https://stenciljs.com/docs/module-bundling#commonjs-dependencies), but it won't fix the problems you are facing. 

Stencil uses `rollup-plugin-commonjs` internally and I can use the `namedExports` property to fix the errors. 

I'll have to do some invesitgating about whether removing CJS entrypoints will affect the `hydrate` build. We don't get a lot of Node users so I'm not sure at the moment.

**Comment by benelan** [comment] 2022-11-14 19:33
After a long wait, Stencil got back to us with the following:

> Regarding the CJS files, there may be some undocumented dependencies, so I'd suggest not removing them now. One of the items on the Stencil team's list is to investigate and document any dependencies.

I'm marking this issue as blocked until Stencil figures it out on their end and lets us know.

**Comment by benelan** [comment] 2023-06-28 19:17
Still going back and forth with Stencil's support over this, but they dropped this gem on us when I provided a repro sample:

> Vitest is not officially supported. 

We are going to try escalating the issue, thanks for your patience everyone.

**Comment by Isaac-o** [comment] 2023-09-21 23:49
Was there anymore information regarding this issue. Seem to be running into the same thing.

**Comment by Isaac-o** [comment] 2023-09-22 00:32
> The Esri Community forum that you linked has the correct answer; you will need to use dynamic imports. Here is a SvelteKit example using the ArcGIS API for JavaScript: https://github.com/benelan/arcgis-esm-samples/tree/main/jsapi-sveltekit-template
> 
> Does that help? If not can you please elaborate on the issue you are facing and/or provide another repro sample that better demonstrates the problem? Thanks!

I was also going to have a look at this solution but it seems no longer be available?

**Comment by jonathandawe-geollect** [comment] 2023-11-06 13:19
@benelan - I'm having major issues trying to use vitetest with the ArcGIS JS API, and I think it might be the issue you are referring to above.  Do you know whether this is something that is being progressed? 

```
SyntaxError: Named export 'getAssetPath' not found. The requested module '@stencil/core/internal/client/index.js' is a CommonJS module, which may not support all module.exports as named exports.  
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@stencil/core/internal/client/index.js';
const { getAssetPath, setAssetPath, setNonce, setPlatformOptions } = pkg;
```

**Comment by kgalliher** [comment] 2023-11-07 22:26
FWIW:  I can reproduce a similar error with a Vitest - Node setup. I can create a `FeatureLayer` but a simple attribute query blows up:

```message: 'Named export \'getAssetPath\' not found. The requested module \'@stencil/core/internal/client/index.js\' is a CommonJS module, which may not support all module.exports as named exports.```

Because I am using my own enterprise, I need to provide an `apiKey` to my feature layer arguments:

```
const fl: FeatureLayer = new FeatureLayer({
    url: "https://machine.domain.com/server/rest/services/BigWorm/FeatureServer/1",
    apiKey: "bBZN5clYULkqT-----blah"
});
```

With a correct token I can access the `FeatureLayer`'s attributes and my tests pass. However, I get more certificate and authentication errors in debug mode using VS Code.

**Comment by pineapplegum** [comment] 2023-12-15 14:20
Trying to run Vitest in a project using ArcGIS SDK for javascript causes this: 

`SyntaxError: Named export 'setAssetPath' not found. The requested module '@stencil/core/internal/client/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@stencil/core/internal/client/index.js';
const { setAssetPath, setPlatformOptions } = pkg;`

**Comment by jonathandawe-geollect** [comment] 2024-02-13 14:31
> @benelan - I'm having major issues trying to use vitetest with the ArcGIS JS API, and I think it might be the issue you are referring to above. Do you know whether this is something that is being progressed?
> 
> ```
> SyntaxError: Named export 'getAssetPath' not found. The requested module '@stencil/core/internal/client/index.js' is a CommonJS module, which may not support all module.exports as named exports.  
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from '@stencil/core/internal/client/index.js';
> const { getAssetPath, setAssetPath, setNonce, setPlatformOptions } = pkg;
> ```

Just to follow this up as it might be helpful to others. I found that I had the best results when testing with the ArcGIS JS API by implementing a [__mocks__ file](https://vitest.dev/guide/mocking.html#:~:text=If%20your%20code%20is%20importing%20a%20mocked%20module%2C%20without%20any%20associated%20__mocks__%20file%20or%20factory%20for%20this%20module%2C%20Vitest%20will%20mock%20the%20module%20itself%20by%20invoking%20it%20and%20mocking%20every%20export.) for the different Classes I was using. 

For example, mocking the ZoomViewModel.ts in the folder:  `\__mocks__\@arcgis\core\widgets\Zoom\ZoomViewModel.ts`

```typescript
import { vi } from "vitest";

const ZoomVM = vi.fn();
ZoomVM.prototype.zoomIn = vi.fn();
ZoomVM.prototype.zoomOut = vi.fn();
ZoomVM.prototype.state = "ready";
ZoomVM.prototype.canZoomIn = true;
ZoomVM.prototype.canZoomOut = false;

export default ZoomVM;
```

You can then test this in a component like so (example for React):

```typescript
import MapView from "@arcgis/core/views/MapView";
import ZoomVM from "@arcgis/core/widgets/Zoom/ZoomViewModel";
import { vi } from "vitest";
import { fireEvent, themedRender } from "../../../test/test-utils";
import ZoomMenu from "./ZoomMenu";

vi.mock("@arcgis/core/views/MapView");
vi.mock("@arcgis/core/widgets/Zoom/ZoomViewModel");

describe("ZoomMenu", () => {
  let mapView: __esri.MapView;
  let zoomVM: ZoomVM;

  beforeEach(() => {
    // Render the ZoomMenu component:
    mapView = new MapView();
    zoomVM = new ZoomVM();
  });
  it("renders ZoomMenu component", () => {
    const view = themedRender(<ZoomMenu />);

    // Get the zoom buttons:
    const zoomInButton = view.getByRole("button", { name: "Zoom in" });
    const zoomOutButton = view.getByRole("button", { name: "Zoom out" });

    fireEvent.click(zoomInButton);
    expect(zoomVM.zoomIn).toHaveBeenCalled();

    fireEvent.click(zoomOutButton);
    expect(zoomVM.zoomOut).toHaveBeenCalled();
  });
});
```

**Comment by slegaitis** [comment] 2024-08-12 12:01
Having the same issue with any components that use MapView

**Comment by benelan** [comment] 2024-12-05 20:50
This issue should be resolved now that Calcite migrated away from StencilJS. You can test on `@arcgis/core@next` and/or `@esri/calcite-components@next` to verify. Here is a SvelteKit repro sample that no longer has build errors: 
https://stackblitz.com/edit/sveltekit-ssr-arcgis-core?file=src%2Froutes%2F%2Bpage.svelte

The `ResizeObserver is not defined` error is expected because `@arcgis/core` maps depend on browser APIs. To resolve the error, make sure to use a dynamic import so the map component gets rendered on the client.

```js
  import { onMount } from "svelte";
  let EsriMap;
  onMount(async () => {
    const module = await import("../components/EsriMap.svelte");
    EsriMap = module.default;
  });
```


Can someone experiencing Vitetest errors please test on `next` to see if the issues are still reproducible? If they are, can someone provide a reproduction sample? Thanks!

**Comment by geospatialem** [comment] 2024-12-16 20:35
Closing the above out with the resolution [Ben mentions above](https://github.com/Esri/calcite-design-system/issues/5077#issuecomment-2521379276). 

If folks encounter vitetest issues, we recommend opening a new issue with a repro case for the team to diagnose further.

**Closed by geospatialem** 2024-12-16 20:35 UTC
Labels: bug, 2 - in development, need more info
