### ISSUE TITLE
Split-button (Rounded Style)

### ISSUE THREAD

**Issue by AdamWMoqrane** [Esri/calcite-design-system#9738] opened 2024-07-05 21:45 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

![image](https://github.com/Esri/calcite-design-system/assets/83651264/2edcd0e4-126f-4b10-926b-a768fa838e2f)

**Split Button Request with Rounded Style Description:**

This feature request is for a split button that retains all the existing behaviors of the current rectangular split button but incorporates a rounded style. The rounded split button will have the following characteristics:

- **Appearance:** The button will feature smooth, rounded edges for a modern, polished look while maintaining the same color scheme and iconography as the rectangular split button.
- **Functionality:** The split button will continue to provide the same interactive behaviors, including the ability to toggle between primary and secondary actions. Users can click the main button for the primary action or click the dropdown arrow to access additional options.
- **Responsive Design:** The rounded split button will adapt to various screen sizes and maintain its functionality and aesthetics across different devices and resolutions.
- **Accessibility:** Ensuring that the rounded split button is fully accessible, with appropriate ARIA labels, keyboard navigation support, and focus indicators.
- **Consistent Behavior:** The split button will preserve all existing behaviors, including hover effects, click animations, and state changes (e.g., active, disabled) to ensure a seamless transition for users familiar with the rectangular version.

By implementing this rounded style, the split button will provide a visually appealing and user-friendly experience while maintaining the robust functionality users rely on.

### Acceptance Criteria

Maintain the following and add "Style rounded:

![image](https://github.com/Esri/calcite-design-system/assets/83651264/83dc2771-fffd-47f4-9637-e98519fa90d1)

### Which Component

Split Button

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Knowledge

**Comment by geospatialem** [comment] 2024-07-05 21:50
Potentially related to the design token epic effort in https://github.com/Esri/calcite-design-system/issues/7180, targeted for July 2024.

**Comment by geospatialem** [comment] 2024-08-28 21:11
Closing as a duplicate of https://github.com/Esri/calcite-design-system/issues/7458. Added the above context to [this comment](https://github.com/Esri/calcite-design-system/issues/7458#issuecomment-2316258695).

**Closed by geospatialem** 2024-08-28 21:11 UTC
Labels: enhancement, 0 - new, estimate - 2, impact - p1 - need for current milestone, needs milestone, ArcGIS Knowledge, design-tokens, calcite-components-react, calcite-components
