### ISSUE TITLE
Calcite Stepper: Issues with disabled state, change events, and styles in v2.0.0

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-design-system#8397] opened 2023-12-11 20:26 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

I found the following issues when testing the stepper on calcite-components v2.0.0. They are reproducible in the linked repro sample.
1. It is not possible to disable the next/previous step action buttons when the stepper is in single step view mode.
2. The `onCalciteStepperItemChange` event does not emit when switching to a step that is disabled, or when switching to the first step (using the step action buttons)
3. The `heading`s for non-disabled stepper items are not visible.
4. The content for disabled stepper items is not visible.

### Expected Behavior

1. It should be possible to disable the next/previous step action buttons, and if possible they should be disabled if the next or previous step is marked as disabled.
2. The `onCalciteStepperItemChange` should always emit when a step changes.
3. The headings should always be visible
4. The content should always be visible.

### Reproduction Sample

https://codesandbox.io/p/sandbox/runtime-morning-tqdjmw?file=%2Fsrc%2FApp.js%3A15%2C40

### Reproduction Steps

1. Open the repro sample
2. Switch between steps using the next/previous action buttons
3. View the console log to see the stepper item change events.

### Reproduction Version

2.0.0

### Relevant Info

Tested in Chrome 120.0.6099.71 and Firefox 122.0a1

### Priority impact

p1 - need for current milestone

### Impact

Needed for updating the underlying theme functionality for developer website.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Developer Experience

**Comment by jcfranco** [comment] 2023-12-13 01:02
Created a [vanilla repro case](https://codepen.io/jcfranco/pen/YzBbKzV?editors=1000) for comparison purposes based on @noahmulfinger's sample.

Prior to the responsiveness updates, disabled steps could not be accessed, so we need to handle this path as well. There may be some UI/UX tweaks needed as well. cc @anveshmekala @SkyeSeitz @ashetland

**Comment by anveshmekala** [comment] 2023-12-13 18:12
Hi @noahmulfinger , Thanks for testing the new stepper single view layout. Some of the UX behavior is preserved to match the existing workflow. Regarding the change event not emitted when switching to first step, i am able to reproduce this and will work on the fix.  For the other issues mentioned , some of them can be added as enhancement.

1. Currently we do not offer disabling `next` and `previous` buttons .The idea was to allow user to access enabled stepper-item which falls after the disabled step or before the disabled ones. Disabling `next/previous` buttons can be optional , will get this added as part of enhancement.

2. `onCalciteStepperItemChange`  not emitted when switching to a `disabled` step is by design since change events are emitted only when there is a change in selection. In the multiple view layout a user cannot select `disabled` `stepper-item` hence change event isn't emitted and we are preserving similar behavior. Can sense confusion here as there is no option to select in single view mode and switching to a specific stepper-item is viewed as selection.  

3. Currently in V2.0 ,the `heading` is visible for all stepper-items in single view layout. Please let us know if i am missing something. Used https://codesandbox.io/p/sandbox/runtime-morning-tqdjmw?file=%2Fsrc%2FApp.js%3A15%2C40 for testing.
4. The content is hidden for `disabled` `stepper-item` to match the behavior of multiple view layout where user cannot select a `disabled` `stepper-item` and content is only visible when `selected`.  Perhaps we can display content for `disabled` items irrespective of view layout. Thoughts? 

cc @jcfranco @SkyeSeitz @ashetland

**Comment by noahmulfinger** [comment] 2023-12-13 19:35
@anveshmekala Thanks for the info. 

For item 3, I still see the `heading` is not visible, but this is only in macOS dark mode. This is what i see: ![Screenshot 2023-12-13 at 11 15 55 AM](https://github.com/Esri/calcite-design-system/assets/6539297/c48cf7d2-1330-489c-9f7d-1b7ec04ac03e)


For item 4, personally I think the current behavior of hiding the content for disabled steps is fine, as long as the step isn't able to be selected (in reference to item 1). 

For reference, we are using the stepper for a set of forms in a workflow within a modal. The user has to fill out a form to continue to the next step. This is why the single view mode next/previous buttons not being disabled is not ideal. But not sure if that's a recommended/expected use case for the stepper.

**Comment by anveshmekala** [comment] 2023-12-13 20:26
i see the issue with `heading` now and step-bar colors are  inconsistent. 

Regarding the previous/next step, the use case mentioned makes a good point to disable previous and next step. We'll add that as a opt-in feature.  Thanks @noahmulfinger

**Comment by anveshmekala** [comment] 2023-12-14 18:45
Hi @noahmulfinger , the dark-mode issue is fixed with `2.1.0-next.8` version of calcite-components-react.  

https://codesandbox.io/p/sandbox/sad-babbage-nfdd9n

**Comment by DitwanP** [comment] 2023-12-15 19:02
🍰 Verified locally on `2.1.0-next.9`

https://github.com/Esri/calcite-design-system/assets/60022782/cecf5258-6de3-44a1-b5d9-b60a857ab7e9

**Closed by DitwanP** 2023-12-15 19:02 UTC
Labels: bug, p - high, 3 - installed, ArcGIS Developer Experience, p1 - need for current milestone, calcite-components-react, calcite-components
