### ISSUE TITLE
`input-time-zone` emits multiple open/close events when toggling `open`

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#9315] opened 2024-05-10 22:50 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When enabling the `input-time-zone` component's `open` prop, events are emitted in this order:
1. `calciteInputTimeZoneOpen`
2. `calciteInputTimeZoneBeforeOpen`
3. `calciteInputTimeZoneOpen`

When disabling the `input-time-zone` component's `open` prop, events are emitted in this order:
1. `calciteInputTimeZoneClose`
2. `calciteInputTimeZoneBeforeClose`
3. `calciteInputTimeZoneClose`

### Expected Behavior

Presumably the first `calciteInputTimeZoneOpen` and `calciteInputTimeZoneClose` events never occur.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/BaeaXom

### Reproduction Steps

1. Visit the sample and open the console
2. Click the **Toggle time zone input** button a few times and see the order of emitted events appear in the console

### Reproduction Version

2.8.0

### Relevant Info

Encountered while investigating a workaround for [the issue][1] where opened overlays do not dismiss when clicking outside of them but on an element that stops event propagation.

[1]: https://github.com/Esri/calcite-design-system/issues/9013

### Priority impact

p3 - want for upcoming milestone

### Impact

Impact is minimal since we don't currently make use of these `input-time-zone` events.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by jcfranco** [comment] 2024-07-26 20:18
Picking this one up since I found out the cause of this while working on #9018. I think this one is doable for this upcoming release. cc @geospatialem

**Comment by geospatialem** [comment] 2024-07-30 19:09
Reallocated to August for additional testing and follow-up! 💪🏻

**Comment by DitwanP** [comment] 2024-08-15 16:31
🍡 Verified on `2.12.0-next.16`
https://codepen.io/Ditwan-Price/pen/GRbyrZY?editors=1011

**Comment by nwhittaker** [comment] 2024-09-05 14:57
@DitwanP, can we reopen this issue? I'm not seeing any change in behavior in your codepen nor `2.12.1` when I use the toggle buttons to open/close the time zone dropdown:

<img width="663" alt="Screenshot 2024-09-05 at 10 50 56 AM" src="https://github.com/user-attachments/assets/69d8b259-977e-464f-825e-04848c1467df">

**Comment by geospatialem** [comment] 2024-09-05 15:06
> @DitwanP, can we reopen this issue? I'm not seeing any change in behavior in your codepen nor `2.12.1` when I use the toggle buttons to open/close the time zone dropdown:
> 
> <img alt="Screenshot 2024-09-05 at 10 50 56 AM" width="663" src="https://private-user-images.githubusercontent.com/421496/364829832-69d8b259-977e-464f-825e-04848c1467df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDkwMzEsIm5iZiI6MTcyNTU0ODczMSwicGF0aCI6Ii80MjE0OTYvMzY0ODI5ODMyLTY5ZDhiMjU5LTk3N2UtNDY0Zi04MjVlLTA0ODQ4YzE0NjdkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNTA1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzFiNmZjNTMzNDc2YzM1NjJkNDFiNmRiMGI3NTgwNjQ5NjgzNGRjNDJjMDU5NjQyNDdhNWJkOTM0NzNjMDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qs3TYm6-l9Z7IO4fPP4JQKlZXxFgpC1dc0yBMsiL6SM">

Confirmed the above is not mitigated in `2.12.1` - reopening and will assign to a milestone soon.

**Comment by geospatialem** [comment] 2024-09-09 18:43
Verified in `2.12.2-next.1` with JavaScript (via the [codepen sample](https://codepen.io/nwhittaker-esri/pen/BaeaXom)), accessing the component via mouse and keyboard. 🎉 

![image](https://github.com/user-attachments/assets/84ae6da5-870a-4b17-a08a-e888e1e37207)

**Closed by geospatialem** 2024-09-09 18:43 UTC
Labels: bug, 4 - verified, p - medium, ArcGIS Field Apps, estimate - 8, impact - p2 - want for an upcoming milestone, calcite-components, p3 - want for upcoming milestone
