### ISSUE TITLE
Keyboard navigation issue in calcite-list

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-design-system#7254] opened 2023-06-30 20:44 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-components/issues) to avoid duplicates

### Actual Behavior

When using custom logic to enable/disable items in the calcite-list, items which were previously disabled and reenabled get skipped during keyboard navigation.

### Expected Behavior

I would expect to be able to tab through all the items, even if they were previously disabled and reenabled.

### Reproduction Sample

https://codepen.io/nid13240/pen/VwVmzpx

### Reproduction Steps

1. open the codepen above - the logic to enable/disable items is there to mimc some logic we have in the Map Viewer
2. select the first item in the list with your keyboard (the next 2 items should become disabled)
3. deselect the first item in the list (those items should become reenabled)
4. try to tab through the rest of the list
5. notice the tab skips those 2 items which were previously disabled

### Reproduction Version

1.4.3

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment] 2023-07-09 23:36
It looks like this one is mitigated when using the arrow keys. 👍🏻 

However, keyboard a11y is not mitigated with the `tab` or `tab` + `shift` keys for navigating, where `list-item` slotted actions are still skipped with https://codepen.io/geospatialem/pen/XWyzpXX. @driskull Is the expectation to also account for `tab` and `shift` + `tab`? If not, I can update the doc.


![verify-list-keyboard-a11y](https://github.com/Esri/calcite-design-system/assets/5023024/32cbad00-5bcf-4760-aafa-42d6c760af13)

**Comment by driskull** [comment] 2023-07-10 17:22
@geospatialem this might actually be unrelated. Its something that the `interactive` helper is doing. Can we get a separate issue for @jcfranco?

The issue is that the tabindex is being set to -1 but not being removed. @jcfranco I don't think the tabindex should be set at all since this component is set to "managed".

**Comment by geospatialem** [comment] 2023-07-18 19:58
New issue created via #7335, closing the above out.

**Closed by geospatialem** 2023-07-18 19:58 UTC
Labels: bug, 4 - verified, ArcGIS Map Viewer, p3 - want for upcoming milestone
