### ISSUE TITLE
[calcite-dropdown] odd behavior when inside a scrollable container

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-design-system#8685] opened 2024-02-01 22:48 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

calcite-dropdown is not shown correctly when it's started as opened below the fold inside a scrollable container. If I click the button at this point nothing will happen, the dropdown will open if I click it a second time.  A side note, if I scroll the container after the dropdown shows up it will stay fixed in that position even if I scrollwheel the trigger button out of view.

### Expected Behavior

- The dropdown should display as opened correctly even if it's started out of view inside a scrollable container
- The dropdown should stay together with the trigger button when I use the mousewheel to scroll the container

### Reproduction Sample

https://codepen.io/rpanichakit/pen/vYPRVQN?editors=1000

### Reproduction Steps

1. open the Codepen link  https://codepen.io/rpanichakit/pen/vYPRVQN?editors=1000
2. scroll the div with the orange background down to the bottom
3. observe that the dropdown is not shown even though it has `open` prop set
4. click the trigger button once and see that nothing happens
5. click the trigger button again and see the dropdown shows up
6. use the mousewheel to scroll the div up and down to see the dropdown stay put while the trigger scrolls away.

### Reproduction Version

2.4.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by driskull** [comment] 2024-03-14 23:16
If we call ` connectFloatingUI` again in `componentDidLoad` this seems to be fixed.

We would probably need to do that for all FloatingUI components so that these scrolling listeners are setup correctly. We need to maintain the call in `connectedCallback` as well for when an element is just moved in the DOM.

@jcfranco if this sounds good I can proceed.

since `connectFloatingUI` is also called when the reference and floating elements are created, maybe we should debounce the call to `connectFloatingUI` as well?

**Comment by jcfranco** [comment] 2024-03-20 23:56
Assigning to this milestone as @driskull has a PR ready. cc @geospatialem

**Comment by DitwanP** [comment] 2024-03-22 20:33
Verified on `2.7.0-next.14`

Note: the behavior mentioned in the issue is resolved but I want to bring attention to the clunky visuals that happen when scrolling up. Not sure if there's anything we can do about it but in case there is, here's a video:


https://github.com/Esri/calcite-design-system/assets/60022782/577f55b8-2787-437c-9d12-061b7fd9ff56

**Closed by DitwanP** 2024-03-22 20:33 UTC
Labels: bug, 3 - installed, p - medium, ArcGIS Online, p4 - not time sensitive, calcite-components, spike complete
