### ISSUE TITLE
[List] - Filtering the list component should not filter out nested list items

### ISSUE THREAD

**Issue by sagewall** [Esri/calcite-design-system#8566] opened 2024-01-08 17:04 UTC
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

In the new layer list widget, redesigned to use calcite, if you search layerlist by the name of a Group Layer, all the sublayers within that Group Layer are filtered out because they do not match the search terms. It seems like if users are searching for a particular group layer, they also want to see the content of that group layer.

### Acceptance Criteria

The ability for a list component to not filter out nested list items.

### Relevant Info
https://codepen.io/sagewall/pen/MWxewRY

### Which Component

List

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by sagewall** [comment] 2024-01-16 16:11
@geospatialem is there any way to get this prioritized?  Based on our recent map jam feedback it seems pretty important.
cc @driskull @asangma

**Comment by driskull** [comment] 2024-01-16 17:09
Since filtering is something new that wasn't there previously, we could always disable it until it supports our use case.

**Comment by sagewall** [comment] 2024-01-18 12:45
Thought I'd comment that this also effects the Map Viewer, Experience Builder, and Instant Apps teams as well.

**Comment by zaramatheson** [comment] 2024-01-18 16:52
Also a high priority for Map Viewer

**Comment by thming** [comment] 2024-01-19 06:17
Yes, this would be a high priority for Experience Builder as well.

We have updated to the new LayerList widget in the upcoming release and I am also seeing the behavior during our testing:
![image](https://github.com/Esri/calcite-design-system/assets/44151116/b6a7007d-dc38-4937-823d-69ac941459c8)

**Comment by driskull** [comment] 2024-01-19 17:16
I think we can close this issue. The list-item allows for providing metadata. The metadata can contain the parent item's title which would support the requested workflow.

**Comment by geospatialem** [comment] 2024-08-06 20:45
Confirmed with Sage that List now has some properties that allow custom filtering, such as `metadata` and `filterProps`:
- List filterPropsprop: https://codepen.io/geospatialem/pen/ZEdKbaZ
- List metadata prop: https://codepen.io/geospatialem/pen/gOEWqEO

Closing as unplanned.

**Closed by geospatialem** 2024-08-06 20:45 UTC
Labels: enhancement, p - high, 0 - new, needs triage, ArcGIS Maps SDK for JavaScript, ArcGIS Experience Builder, ArcGIS Instant Apps, ArcGIS Map Viewer, impact - p2 - want for an upcoming milestone, calcite-components, c-list
