### ISSUE TITLE
Date picker: year is slightly cut off

### ISSUE THREAD

**Issue by jlias-devtester** [Esri/calcite-design-system#6410] opened 2023-02-01 18:21 UTC
### Actual Behavior

The year in the date-picker component is slightly cut off on the end:

![image](https://user-images.githubusercontent.com/62298389/216129029-df56fa81-4043-4794-b426-c057ff8f04df.png)

### Expected Behavior

The year shouldn't be cut off

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/KKxEMoK

### Reproduction Steps

1. Visit the [sample](https://codepen.io/mac_and_cheese/pen/KKxEMoK) on Mac OS
2. Observe the year is cut off

### Reproduction Version
1.1.0

### Relevant Info
Seems to be specific to Mac OS across browsers (Chrome, FF, Safari). Windows browsers appear to be unaffected (tested on Chrome, FF, Edge).

### Esri team

ArcGIS Online

**Comment by benelan** [comment] 2023-02-01 20:12
Hi @jlias-devtester - did you close the issue because you figured out a solution? I'm not able to reproduce this on my end with this sample https://codepen.io/benesri/pen/qByQYyJ

If you are still experiencing the issue can you provide some additional information, such as browser, operating system, etc? A sample that reproduces the issue would also be very helpful. Thanks!

**Comment by macandcheese** [comment] 2023-03-27 16:09
It's reproducible in scale "L" : https://codepen.io/mac_and_cheese/pen/KKxEMoK?editors=1010

**Comment by geospatialem** [comment] 2023-03-27 16:22
> It's reproducible in scale "L" : https://codepen.io/mac_and_cheese/pen/KKxEMoK?editors=1010

Am able to reproduce the `scale="l"` bug in https://codepen.io/mac_and_cheese/pen/KKxEMoK on Mac OS across browsers (Chrome, FF, Safari), but Windows browsers are unaffected (tested on Chrome, FF, and Edge).

**Comment by DitwanP** [comment] 2024-10-28 20:25
🍡 Verified on `2.14.0-next.18` 
https://codepen.io/Ditwan-Price/pen/BaXYEoR

**Closed by DitwanP** 2024-10-28 20:25 UTC
Labels: bug, p - low, 3 - installed, ArcGIS Online, estimate - 3, c-datepicker, low risk
