### ISSUE TITLE
`<calcite-select>`: `value` property/attribute is not respected

### ISSUE THREAD

**Issue by hcampos-professional** [Esri/calcite-design-system#7311] opened 2023-07-12 14:44 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a `<calcite-select>` is provided with the `value` of one of it's `<calcite-option>`, that value is not respected.

### Expected Behavior

Is is expected that the `value` property of the `<calcite-select>` is respected if none of the `<calcite-option>` elements have a `selected` attribute/property.

### Reproduction Sample

https://codepen.io/hccampos/pen/VwVyEpw

### Reproduction Steps

1. Open https://codepen.io/hccampos/pen/VwVyEpw
2. Notice that the first `<calcite-select>` displays "Foo" despite having `value="bar"` set on it.
3. Notice that the second `<calcite-select>` correctly displays "Bar" since the corresponding option has the `selected` attribute.

### Reproduction Version

1.4.2

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment] 2023-08-07 18:47
For the workaround, set the `selected` property on the `calcite-option` to update the parent (`select`) value.

**Comment by jcfranco** [comment] 2024-05-16 06:46
This is a duplicate of https://github.com/Esri/calcite-design-system/issues/4461 and will be available in the upcoming release (see [updated repro case](https://codepen.io/jcfranco/pen/XWwmNYX)).

**Closed by jcfranco** 2024-05-16 06:46 UTC
Labels: bug, 0 - new, p - medium, has workaround, ArcGIS Maps SDK for JavaScript, estimate - 5, p4 - not time sensitive, calcite-components
