### ISSUE TITLE
UI that cancels `click` events prevents popovers from auto-closing

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#9013] opened 2024-03-28 02:50 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Given a popover with `auto-close` enabled, clicking an element that prevents propagation of the `click` event causes the popover to remain open.

### Expected Behavior

Clicking an element that prevents propagation of the `click` event _does not_ cause the popover to remain open.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/MWRvPzQ

### Reproduction Steps

1. Visit the repro sample and click the **Layer information** button to open the popover.
2. With the popover still open, click the **Button with event cancelation** button and observe the popover remains opened.
3. Optionally click a blank area in the document body and see the popover closes.

### Reproduction Version

2.7.0

### Relevant Info

Possibly regressed by https://github.com/Esri/calcite-design-system/pull/8983. Is it possible to restore the handler to the `capture` phase and inspect the event's target there to see if it's `disabled` or `aria-disabled` instead?

Other components that exhibit the same regressed behavior: `combobox`, `dropdown`, and `input-time-zone`.

### Regression?

2.6.0

### Priority impact

p2 - want for current milestone

### Impact

This change in behavior is breaking our tests in ways that are not easily solvable and preventing us from upgrading to Calcite 2.7. Going forward, it also prevents us from implementing UI with any sort of `click` cancelation.

A workaround could be to have our handlers relay a new `click` event to the `window`, but that doesn't solve the problem where the cancelation was intended to prevent bubbling up to another handler that is also on the `window`.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by timmorey** [comment] 2024-04-05 14:12
This issue is currently blocking us from adopting 2.7+ in field-maps-designer.  Over the last 5+ yrs of development, we have accumulated a number of `stopPropagation()` calls on click events in various parts of the UI.  Each of these is now effectively a "dead spot" in the app where a click interaction will fail to close a popover/dropdown/etc.

Maybe we could find better solutions than doing `stopPropagations()` in some of these places, but the effort to re-evaluate each would be quite large.  I have to presume that a number of other apps are in a similar situation, since `stopPropagation()` is a common tool to control how events are handled.

**Comment by jcfranco** [comment] 2024-04-19 07:34
@nwhittaker @timmorey Apologies for the delayed response. We are exploring alternative solutions and potential workarounds. Worst-case scenario, we may need to revert #8983 for the upcoming release and aim to reinstall in May.

It's important to note that we want all components to use the target/bubbling event phase for consistency and to meet developer expectations. Currently, relying on the capture phase is problematic as it complicates other fixes we need to implement.

> Maybe we could find better solutions than doing stopPropagations() in some of these places, but the effort to re-evaluate each would be quite large.

Agreed. It'll take some effort to re-evaluate `stopPropagation()` usage, but it seems like a worthwhile task to help prevent disruptions and bugs.

cc @geospatialem

**Comment by nwhittaker** [comment] 2024-04-19 14:28
>It's important to note that we want all components to use the target/bubbling event phase for consistency and to meet developer expectations. Currently, relying on the capture phase is problematic as it complicates other fixes we need to implement.

@jcfranco is it possible to make a distinction: Events targeting elements inside a Calcite shadow-dom vs. events targeting elements outside a Calcite shadow-dom? Where the former events use bubbling and the latter use capturing?

Alternatively, is going back to pointer events[^1] for these types of "outside click" handlers an option? It's not perfect, but might be less likely to conflict with developer flows that are listening for mouse events.

[^1]: https://github.com/Esri/calcite-design-system/pull/8943

**Comment by jcfranco** [comment] 2024-04-22 19:26
> is it possible to make a distinction: Events targeting elements inside a Calcite shadow-dom vs. events targeting elements outside a Calcite shadow-dom? Where the former events use bubbling and the latter use capturing?

I could be missing something, but this might not help with eventing expectation concern. It'll be simpler to use the same phase. Component composition might also make this tricky as the targeted component could be used within either light or shadow DOM.

> Alternatively, is going back to pointer events[1](https://github.com/Esri/calcite-design-system/issues/9013#user-content-fn-1-37eef931e2d91606656d13201c1141f4) for these types of "outside click" handlers an option? 

I'd like to keep `click` for these contexts.

--- 

Workaround-wise, would it be possible to set up something like [the following](https://codepen.io/jcfranco/pen/bGJmPGB) into your environments? The key parts of the workaround are:

1. hijack `Event.prototype.stopPropagation` to extend default behavior 👇 (a custom helper to stop propagation could also be used, but went with the simplest setup)
2. emits custom `click` event directly on `window` (should help bypass any event handlers in between and toggles popovers)
    * alternatively, this could emit a `KeyboardEvent` of type `keydown` with `Escape` as the pressed `key`

**Comment by nwhittaker** [comment] 2024-04-23 00:05
>I could be missing something, but this might not help with eventing expectation concern. It'll be simpler to use the same phase.

My point was there could be a distinction between events that can be canceled and ones that cannot (e.g. outside clicks). For the ones that cannot, they should be listened for in the capture phase to mitigate cancelation. There's the added complexity of checking for disabled reference elements, but it's with significant benefit to the consumer.

>Component composition might also make this tricky as the targeted component could be used within either light or shadow DOM.

Wondering what you're thinking of here because the event's `composedPath()` function gets everything including elements in shadow DOMs.

>Workaround-wise, would it be possible to set up something like [the following](https://codepen.io/jcfranco/pen/bGJmPGB) into your environments?

I did address this in the issue description. As a general workaround, it fails for the case where I have other `click` handlers on the window that I want to stop the event for. I also suspect monkey patching native classes is something the team wants to avoid.

---
Ideally the outside-click handling just works without impact to the consumer code. Workarounds aside, I guess I'm left wondering what are the technical blockers that make that not achievable?

**Comment by wei8123** [comment] 2024-05-15 21:29
Hi, this issue effects the click event in ArcGIS Experience Builder Shadow cast tool. 
![2024-05-15_14-28-31](https://github.com/Esri/calcite-design-system/assets/37641492/5132bfd1-fb95-43ea-af4e-d76f35d5efb8)

This is also reproducible with a plain Calcite app. Here's a simple app which reproduces the problem. 
https://codepen.io/hccampos/pen/WNBvLqK

**Comment by jcfranco** [comment] 2024-05-20 23:57
I meant to follow up on this sooner, but we are not considering this a regression and will proceed to close for the following reasons:

1. The event phases our components use are not publicly documented and are subject to change.
2. Our components aim to follow developer expectations and therefore use the bubbling/target phase for event handling.
    1. Popover and tooltip were the only outliers using the capture phase due to the initial implementation. We recently refactored popover to use a different phase and will do the same for tooltip.
4. Stopping event propagation can have unintended side effects and break expectations of how events normally work across components (this is important for a low-level component library).
    1. This will also cause issues with other components currently (e.g., dropdown).
    2. It is very likely to encounter the same issue with other component libraries.

I synced up with @nwhittaker a while back, and their team will pursue an app-level workaround. Not sure if the approach is ready to be shared at this time.

@wei8123 In your example, the `stopImmediatePropagation` is preventing all click handlers from processing the event (including the popover). Would any of the [following workarounds](https://codepen.io/jcfranco/pen/eYaJaGo) help?

**Comment by nwhittaker** [comment] 2024-05-22 00:03
>Not sure if the approach is ready to be shared at this time.

Here's our current working workaround. I don't know how comprehensive it is, but it seems to work well so far. The basic approach is to create a `click` capture listener on the document whenever a target opens and remove it when the target closes. If the listener is invoked, it closes the target if the click occurred outside of the target or any reference-element.

```ts
import {
  CalciteComboboxCustomEvent,
  CalciteDropdownCustomEvent,
  CalciteInputTimeZoneCustomEvent,
  CalcitePopoverCustomEvent,
} from '@esri/calcite-components'

type CalciteOutsideClickCustomEvent<T> = CalciteComboboxCustomEvent<T>
  | CalciteDropdownCustomEvent<T>
  | CalciteInputTimeZoneCustomEvent<T>
  | CalcitePopoverCustomEvent<T>

type HTMLCalciteOutsideClickElement = CalciteOutsideClickCustomEvent<void>['target']

// Workaround for Esri/calcite-design-system#9013.
export default function patchComponentsWithOutsideClickHandlers() {

  // Track the opened targets and their outside-click handlers.
  const targets = new WeakMap<HTMLCalciteOutsideClickElement, (event: MouseEvent) => void>()

  window.addEventListener('calciteComboboxBeforeOpen', onBeforeOpen)
  window.addEventListener('calciteComboboxBeforeClose', onBeforeClose)

  window.addEventListener('calciteDropdownBeforeOpen', onBeforeOpen)
  window.addEventListener('calciteDropdownBeforeClose', onBeforeClose)

  window.addEventListener('calciteInputTimeZoneBeforeOpen', onBeforeOpen)
  window.addEventListener('calciteInputTimeZoneBeforeClose', onBeforeClose)

  window.addEventListener('calcitePopoverBeforeOpen', onBeforeOpen)
  window.addEventListener('calcitePopoverBeforeClose', onBeforeClose)

  // Register the opening target and add a one-off outside-click handler for it.
  function onBeforeOpen(event: CalciteOutsideClickCustomEvent<void>) {
    const target = event.composedPath()[0] as HTMLCalciteOutsideClickElement

    if ('autoClose' in target && !target.autoClose) return
    if (targets.has(target)) return

    const referenceElement = referenceElementOf(target)

    targets.set(target, onClick)
    window.addEventListener('click', onClick, { capture: true })

    function onClick(clickEvent: MouseEvent) {
      const shouldKeepOpen = referenceElement === clickEvent.target || clickEvent.composedPath().includes(target)

      // Known issue: triggers multiple close events on `input-time-zone` (Esri/calcite-design-system#9315)
      target.open = shouldKeepOpen
    }
  }

  // Unregister the closing target and remove the outside-click handler.
  function onBeforeClose(event: CalciteOutsideClickCustomEvent<void>) {
    const target = event.composedPath()[0] as HTMLCalciteOutsideClickElement,
      onClick = targets.get(target)

    if (!onClick) return

    window.removeEventListener('click', onClick, { capture: true })
    targets.delete(target)
  }
}

function referenceElementOf(target: HTMLCalciteOutsideClickElement) {
  if (!('referenceElement' in target)) return
  const { referenceElement } = target

  if (typeof referenceElement === 'string') {
    const root = target.getRootNode() as Document | ShadowRoot
    return root.getElementById(referenceElement)
  }

  return referenceElement
}

```

**Comment by jcfranco** [comment] 2024-05-25 02:10
Thanks for sharing your workaround @nwhittaker!

Closing per https://github.com/Esri/calcite-design-system/issues/9013#issuecomment-2121454964.

**Closed by jcfranco** 2024-05-25 02:10 UTC
Labels: bug, 1 - assigned, needs triage, regression, ArcGIS Experience Builder, ArcGIS Field Apps, impact - p2 - want for an upcoming milestone, calcite-components

**Comment by qlqllu** [comment] 2024-06-11 07:06
ExB has a complex layout system. In the builder, we need to stop the propagation of click events when selecting a widget. And the workaround seems not work in ExB, do we miss something?

**Comment by wei8123** [comment] 2024-06-20 22:31
> I meant to follow up on this sooner, but we are not considering this a regression and will proceed to close for the following reasons:
> 
> 1. The event phases our components use are not publicly documented and are subject to change.
> 2. Our components aim to follow developer expectations and therefore use the bubbling/target phase for event handling.
>    
>    1. Popover and tooltip were the only outliers using the capture phase due to the initial implementation. We recently refactored popover to use a different phase and will do the same for tooltip.
> 3. Stopping event propagation can have unintended side effects and break expectations of how events normally work across components (this is important for a low-level component library).
>    
>    1. This will also cause issues with other components currently (e.g., dropdown).
>    2. It is very likely to encounter the same issue with other component libraries.
> 
> I synced up with @nwhittaker a while back, and their team will pursue an app-level workaround. Not sure if the approach is ready to be shared at this time.
> 
> @wei8123 In your example, the `stopImmediatePropagation` is preventing all click handlers from processing the event (including the popover). Would any of the [following workarounds](https://codepen.io/jcfranco/pen/eYaJaGo) help?

Hi @jcfranco, as @qlqllu mentioned above, executing this workaround file in EXB's ```init``` does not solve the problem: 
![2024-06-20_15-30-24](https://github.com/Esri/calcite-design-system/assets/37641492/8134e525-420e-458a-bd08-fb97c36f9845)
Because clicking the problematic button in the 3D-Toolbox widget, does not trigger the events listened in the workaround file (such as ```'calciteDropdownBeforeOpen'```, ```'calciteDropdownBeforeClose'```).
Any idea?

**Comment by jcfranco** [comment] 2024-06-24 19:36
@qlqllu @wei8123 Could you please share more details about your issue? I'm afraid I can't help without additional context. We can also schedule a meeting or call if you’d prefer.

**Comment by qlqllu** [comment] 2024-06-25 06:19
@jcfranco We call the `patchComponentsWithOutsideClickHandlers` function in an ExB app's init process; however, we find neither the `onBeforeOpen` nor `onBeforeClose` callback gets invoked. Do we miss anything?

Here are more details on why we need to stop event propagation. ExB supports nested layout structure. For example, we can add a Button widget inside a Fix panel widget, and both of these widgets need to be selected. So, when the user clicks the Button widget to select it, we have to stop the click event propagation because if not, the user will select the Fix panel widget.

**Comment by ruantao1989** [comment] 2024-07-04 08:23
> Hi, this issue effects the click event in ArcGIS Experience Builder Shadow cast tool. ![2024-05-15_14-28-31](https://private-user-images.githubusercontent.com/37641492/330965491-5132bfd1-fb95-43ea-af4e-d76f35d5efb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODA4NjEsIm5iZiI6MTcyMDA4MDU2MSwicGF0aCI6Ii8zNzY0MTQ5Mi8zMzA5NjU0OTEtNTEzMmJmZDEtZmI5NS00M2VhLWFmNGUtZDc2ZjM1ZDVlZmI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA4MDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNGM1Y2FlMTcxNmE3OTI0MGU0OWE0NDllMjZkYTQ1NGRmYmE5NTM1NzYwNzI4NDY0MGQ1OGRjNjlmNTdlMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sOhwT26e0nhCjYF8gKNmWuTE1SkqyuYHw2_mi-D6N1w)
> 

Hi @jcfranco, 
I created a quick demo to show how we use it in EXB: https://codepen.io/ruantao1989/pen/zYVOqwV
Could you please take a look? 

Thanks!

**Comment by ruantao1989** [comment] 2024-07-15 02:16
I added a demo to show our specific issue: @jcfranco 
https://codepen.io/ruantao1989/pen/qBzOWvg?editors=1000

https://github.com/user-attachments/assets/2ff4986c-78c1-44dd-b76e-bf70fcc2e3f7

1. Outside the map and the calcite DOM, we have a container DOM:
````
    <div id="container" style="border: 2px solid red">
      <div id="mapDiv"> </div>
    </div>
````    

 2. Due to the functionality of EXB, we need to prevent event propagation in the container, 
 However, this causes the ShadowCast calcite component (color-picker) to fail to open
 ````
        /******************************************************
        stopping propagation on click on a container DOM:
        The color picker at the bottom of the ShadowCast component cannot be opened
        ******************************************************/
        document.querySelector("#container").addEventListener("click", (e) => {
          e.stopPropagation();
        });
````

**Comment by jcfranco** [comment] 2024-07-15 22:38
@ruantao1989 If you're able to redirect fake clicks to window without any issue, you could apply a modified version of on of the earlier workarounds:

```ts
document.querySelector("#container").addEventListener("click", (e) => {
  e.stopPropagation();
  
  // workaround: redirect a fake click event to window for popover to listen to
  const fakeEvent = new CustomEvent("click", { detail: 1 });
  fakeEvent.composedPath = () => [e.target];
  window.dispatchEvent(fakeEvent);
});
```

See updated [demo](https://codepen.io/jcfranco/pen/yLdYoMd?editors=1000).

**Comment by qlqllu** [comment] 2024-07-16 03:31
@jcfranco The fake event workaround works. However, I think this solution does not seem very clean, and it may have side effects if an app code listens to the click events on the window. Whenever an app stops the event propagation, it may have this issue and need to find this workaround solution. I still prefer the "capture" phase solution.

Nevertheless, thanks for helping figure out this workaround!

**Comment by jcfranco** [comment] 2024-07-16 18:27
@qlqllu Glad to hear the workaround will work for you.

Regarding your other concerns, please refer to point 3 in the [above discussion](https://github.com/Esri/calcite-design-system/issues/9013#issuecomment-2121454964).

**Comment by ruantao1989** [comment] 2024-08-30 08:50
> ```ts
> document.querySelector("#container").addEventListener("click", (e) => {
>   e.stopPropagation();
>   
>   // workaround: redirect a fake click event to window for popover to listen to
>   const fakeEvent = new CustomEvent("click", { detail: 1 });
>   fakeEvent.composedPath = () => [e.target];
>   window.dispatchEvent(fakeEvent);
> });
> ```
> 
> See updated [demo](https://codepen.io/jcfranco/pen/yLdYoMd?editors=1000).

Hi @jcfranco, 
the workaround you provided before is no longer usable after the calcite update:

1. The Timezone popup of Shadow cast will not be opened

 https://github.com/user-attachments/assets/028d8b83-3034-4d0c-9a3a-556d72c17823



2. If the custom event is delayed, you will find that the Timezone popup will be closed by the custom event
 
https://github.com/user-attachments/assets/ac88d595-3c81-4dee-a255-5bdef701b7a6

Please see this [demo](https://codepen.io/ruantao1989/pen/BagOojz?editors=1000)
@wei8123

**Comment by jcfranco** [comment] 2024-09-17 17:57
@ruantao1989 @wei8123 Apologies for the delayed reply. You'll need to make one small tweak for the workaround to work correctly in your example:

```tsx
document.querySelector("#container").addEventListener("click", (e) => {
  e.stopPropagation();

  const fakeEvent = new CustomEvent("click", { detail: 1 });
  fakeEvent.composedPath = () => e.composedPath();
  window.dispatchEvent(fakeEvent);
});
```

We now pass the composed path in the fake event for any other components checking on an event's path to match their expected target (e.g., `dropdown`).

**Comment by ruantao1989** [comment] 2024-09-25 07:14
Thank you @jcfranco, 

But after my test, it seems that the event from the normal DOM (not in the shadow DOM) does not have ```e.composedPath``` and ```e.composedPath()```;

How can I use the above workaround for this kind of event?
