### ISSUE TITLE
[Alert] Refactor register event

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9499] opened 2024-06-03 22:28 UTC
### Description

Refactor the current `dispatchEvent` to have a register of elements. Can be coupled with the effort of https://github.com/Esri/calcite-design-system/issues/9340

### Proposed Advantages

Updated pattern and consistency across the design system

### Which Component

`alert`

### Relevant Info

https://github.com/Esri/calcite-design-system/blob/570529fdc1bc13f68446c7535dc0e58538e49612/packages/calcite-components/src/components/alert/alert.tsx#L197

https://github.com/Esri/calcite-design-system/blob/570529fdc1bc13f68446c7535dc0e58538e49612/packages/calcite-components/src/components/alert/alert.tsx#L359

Related to epic https://github.com/Esri/calcite-design-system/issues/7200

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by driskull** [comment] 2024-08-09 20:51
Seems like this is a duplicate of https://github.com/Esri/calcite-design-system/issues/9340

**Comment by geospatialem** [comment] 2024-08-12 16:31
> Seems like this is a duplicate of #9340

@driskull They seem separate to me, but we can combine them into one. Is #9340 the preferred issue for tracking? If so I can add the context above into the effort and move it to December closing out the above.

**Comment by driskull** [comment] 2024-08-12 16:34
Reading them again, they are separate but they can be tackled at the same time. 👍

**Comment by DitwanP** [comment] 2024-08-20 19:19
🍠 Verified

**Closed by DitwanP** 2024-08-20 19:19 UTC
Labels: refactor, p - low, 3 - installed, estimate - 3, calcite-components, c-alert
