### ISSUE TITLE
dropdown button with width="full" wider than containing block

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#5903] opened 2022-12-05 23:40 UTC
### Actual Behavior

![image](https://user-images.githubusercontent.com/44481292/205768062-495157a1-7af7-4719-8d64-68656da1b389.png)

The dropdown button is wider than its containing block if the button text has no dashes or spaces.
Button uses `width="full"`.

### Expected Behavior

text is wrapped 

### Reproduction Sample

https://codepen.io/afreitag/pen/GRGPdwQ

### Reproduction Steps

open codepen and observe. Red box displays block dimensions.

### Reproduction Version

next.657

### Regression?

Don't think so

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment] 2022-12-06 17:08
Applicable in the case mentioned above where text has no breaks, such as "`BirdObservationCommentBirdObservationComment`" and where "`_`" characters are present, such as "`Bird_Observation_Comment_Bird_Observation_Comment`".

![image](https://user-images.githubusercontent.com/5023024/205976751-55dd0600-0a27-4a1a-b234-d1ea68c35eba.png)

**Comment by AdelheidF** [comment] 2022-12-08 20:23
will this be part of 1.0?

**Comment by benelan** [comment] 2022-12-08 20:40
How smart do you want this to be; are you expecting it to understand word breaks such as, capitalization, underscores, periods, etc.

>BirdObservationCommentBirdObservation
>Comment

Or just wrap on the overflow
>BirdObservationCommentBirdObservationCom
>ment

**Comment by AdelheidF** [comment] 2022-12-08 20:49
> Or just wrap on the overflow

I think this is fine. Don't you do this already in other places like this?

**Comment by macandcheese** [comment] 2022-12-08 21:34
FWIW, it breaks in a different way when the button is not the dropdown-trigger:
<img width="421" alt="Screen Shot 2022-12-08 at 1 32 07 PM" src="https://user-images.githubusercontent.com/4733155/206572164-831881ef-b3a8-4ccf-822b-3d1446acc134.png">

**Comment by geospatialem** [comment] 2022-12-22 22:41
@AdelheidF We're putting this in a list for Franco when he returns, but due to staffing, this one might land in time for the February release. Will post an update a few weeks into 2023.

**Comment by geospatialem** [comment] 2023-02-28 00:04
Seeking design expertise for the `dropdown` button, if wrapping and/or truncating the text should be considered.

**Comment by Elijbet** [comment] 2023-03-27 03:07
> Seeking design expertise for the `dropdown` button, if wrapping and/or truncating the text should be considered.

@SkyeSeitz I'm assuming we follow the `button` pattern in https://github.com/Esri/calcite-components/issues/5660 where we truncate long text on fixed-width components that should not grow in height? I would think this pattern should be consistent regardless of where the button is slotted, is that so?

**Comment by ashetland** [comment] 2023-03-27 16:23
> > Seeking design expertise for the `dropdown` button, if wrapping and/or truncating the text should be considered.
> 
> @SkyeSeitz I'm assuming we follow the `button` pattern in #5660 where we truncate long text on fixed-width components that should not grow in height? I would think this pattern should be consistent regardless of where the button is slotted, is that so?

Yep, agreed here.

**Comment by Elijbet** [comment] 2023-03-29 20:56
@ashetland @SkyeSeitz How would the tooltip with full button text for sighted users work in this scenario, where the button is slotted as a trigger to dropdown within a block per use-case image provided in the description above?

**Comment by Elijbet** [comment] 2023-04-07 19:19
We caught a bit of a design issue with truncated text `buttons` in https://github.com/Esri/calcite-components/issues/5660 . Mainly that the initial purpose of the tooltip is to provide context beyond what the button text is. To avoid that, we decided we could use HTML `label` for truncated buttons to reveal the full text for sighted users and leave `tooltip` alone to provide additional context. Once the truncated button is merged, this issue will pick up from there to achieve this solution instead. 

<img width="536" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/19231036/230664338-cd485afd-fcba-4440-9e8c-8ac1f3de1507.png">

The conversation was between @macandcheese, @ashetland, and me in the teams. After updating @driskull, we thought the above https://github.com/Esri/calcite-components/pull/6747 could be used as an interim solution. So let's merge that and I'll pick this up after issue #5660 is merged as well.

**Comment by AdelheidF** [comment] 2023-05-10 18:30
What happened???

It was working with @esri/calcite-components@1.3.0-next.2

But it now longer works with @esri/calcite-components@1.3.0 or 1.3.1

**Comment by geospatialem** [comment] 2023-05-10 18:44
This might be related to https://github.com/Esri/calcite-components/pull/6664, which was merged 4 days after the fix above. 

@driskull @Elijbet Would you be able to take a peek to see if `button` inherits parent width as we expect it? Saw some [additional discussion above](https://github.com/Esri/calcite-components/issues/5903#issuecomment-1500570630), which mentioned some design conflicts with `button` from #5660.

**Comment by driskull** [comment] 2023-05-10 19:54
@Elijbet can you take this? Is the screenshot test still working correctly? I wonder what happened.

**Comment by Elijbet** [comment] 2023-05-10 19:58
> @Elijbet can you take this? Is the screenshot test still working correctly? I wonder what happened.

Yep, I'll take a look. It's not supposed to wrap anymore based on the other related issue discussions. Let me see what is the issue.

**Comment by Elijbet** [comment] 2023-05-20 00:41
> What happened???
> 
> It was working with @Esri/calcite-components@1.3.0-next.2
> 
> But it now longer works with @Esri/calcite-components@1.3.0 or 1.3.1

This issue was verified as resolved after the interim solution to wrap the text was implemented, awaiting the design approach to the long text with no breaks. The design decision that followed was to truncate text on buttons with a set height and provide a tooltip with full text for sighted users. This was implemented on the button component, and its installation caused a regression in the dropdown with the nested button. The button text truncation works when the button width is contained within the container, in this nested use case though the width=“full” on the button doesn’t work.

#6958 swapped `display: flex` with `display: block` on the` dropdown host` to allow for the `button` to extend `width="full"`.

Note: This should be scheduled for a future planned breaking change release.

In the meantime, here's a workaround:

```
calcite-dropdown {
  display: block;
}
```

**Comment by ethanbdev** [comment] 2023-06-29 23:48
Ran into this and just wanted to add that it still happens if there are spaces
https://codepen.io/eborgen/pen/qBQmbgm?editors=1010

The workaround still works

**Comment by geospatialem** [comment] 2023-10-23 20:21
Spike efforts of https://github.com/Esri/calcite-design-system/issues/7692 might have similar groupings/relationships .

Consider tackling the spike in coordination with the breaking change in the above issue.

**Comment by jcfranco** [comment] 2023-11-23 00:22
Installed an update to `dropdown` on `rc` that will make it easier to set up truncation in the original use case. You'll need to set 100% width in the dropdown or change its display to block as @Elijbet's suggestion shows. We can't do this reliably for all configurations since it really depends on the way the HTML/CSS is structured. For example, [this](https://codepen.io/jcfranco/pen/dyaezWY) shows the same issue can be seen with block + button.

**Comment by geospatialem** [comment] 2023-12-01 16:23
Verified with `v2.0.0-rc.2` when `calcite-dropdown`'s `width` is set to `100%` per [Franco's comment above](https://github.com/Esri/calcite-design-system/issues/5903#issuecomment-1823688446).

![image](https://github.com/Esri/calcite-design-system/assets/5023024/f689864d-592e-42dd-b40d-dbbb36ebdf9f)

**Comment by AdelheidF** [comment] 2023-12-08 22:08
I tested this fix now with the original (simple) codepen and it seems fixed with 2.0. But when I look at it in Map Viewer it's still not working.

I updated the codepen to display the issue in the right-side flow. It seems that if the `calcite-blocks` are surrounded by `calcite-sortable-list` it's still not working. If you comment out this element it displays correctly.

https://codepen.io/afreitag/pen/GRGPdwQ; 

The workaround no longer works either
```
calcite-dropdown {
  display: block;
}
```

**Comment by jcfranco** [comment] 2023-12-08 22:13
If you set `calcite-sortable-list`'s display to `block`, it'll work.

![Screenshot 2023-12-08 at 2 11 54 PM](https://github.com/Esri/calcite-design-system/assets/197440/98db85da-97be-47fc-be3f-dc46f0ee9085)

**Comment by AdelheidF** [comment] 2023-12-08 22:24
Nice, this works. I will use that.

Is this a workaround or the solution? Basically do you want me to close this issue again?

**Comment by jcfranco** [comment] 2023-12-09 00:31
This would be the solution. The recent change to dropdown makes truncation easier to set up, but we can't handle all cases as it depends on the HTML structure.

**Closed** 2023-12-09 00:34 UTC
Labels: enhancement, breaking change, 4 - verified, p - medium, has workaround, ArcGIS Map Viewer, estimate - 3
