### ISSUE TITLE
closing tab raise javascript exception in console

### ISSUE THREAD

**Issue by oldoldman** [Esri/calcite-design-system#9079] opened 2024-04-08 10:05 UTC
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Hi,
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="module" src="https://js.arcgis.com/calcite-components/2.7.1/calcite.esm.js"></script>
    <link rel="stylesheet" type="text/css" href="https://js.arcgis.com/calcite-components/2.7.1/calcite.css" />
  </head>
  <body>
    <calcite-tabs>
      <calcite-tab-nav slot="title-group">
        <calcite-tab-title tab='tab1' closable>Tab1</calcite-tab-title>
        <calcite-tab-title tab='tab2' closable>Tab2</calcite-tab-title>
        <calcite-tab-title tab='tab3' closable>Tab3</calcite-tab-title>
        <calcite-tab-title tab='tab4' closable>Tab4</calcite-tab-title>
      </calcite-tab-nav>
      <calcite-tab tab='tab1'>
        <calcite-button>tab1</calcite-button>
      </calcite-tab>
      <calcite-tab tab='tab2'>
        <calcite-button>tab2</calcite-button>
      </calcite-tab>
      <calcite-tab tab='tab3'>
        <calcite-button>tab3</calcite-button>
      </calcite-tab>
      <calcite-tab tab='tab4'>
        <calcite-button>tab4</calcite-button>
      </calcite-tab>
    </calcite-tabs>
  </body>
</html>
```
With the above setup, closing any tab will raise
```
tab-nav.tsx:698  Uncaught TypeError: Cannot read properties of undefined (reading 'focus')
    at tab-nav.tsx:698:37
```

### Expected Behavior

no exception will be raised.

### Reproduction Sample

NA

### Reproduction Steps

NA

### Reproduction Version

calcite web component 2.7.1

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment] 2024-04-08 19:48
Duplicate of https://github.com/Esri/calcite-design-system/issues/8587.

**Closed by jcfranco** 2024-04-08 19:48 UTC
Labels: bug, 0 - new, needs triage, Calcite (dev), p4 - not time sensitive, calcite-components
