### ISSUE TITLE
flow-item back button focus issues and tooltip at wrong location

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#6400] opened 2023-01-31 20:50 UTC
### Actual Behavior

![image](https://user-images.githubusercontent.com/44481292/215876929-ed5b2c4b-0ca9-4aeb-a6eb-0be267e93ace.png)

After creating the second flow-item I want to have the focus set on the back button.

Try 1:
`flowItem2.setFocus();`
-> doesn't set the focus on back button

Try 2: 
`requestAnimationFrame(() => flowItem2.setFocus());`
-> doesn't set the focus on back button
-> this method worked for me with beta.99, but I can't repro it via the codepen
  
Try 3:
`setTimeout(() => flowItem2.setFocus(), 100);`
-> sets the focus on back button, but tooltip is somewhere else

Try 4:
`setTimeout(() => flowItem2.setFocus(), 1000);`
-> sets the focus on back button, with tooltip on it, but it takes too long to wait for the correct focus

### Expected Behavior

1. requestAnimation should set the focus; no random timeout required
2. tooltip is always next to the back button

### Reproduction Sample

https://codepen.io/afreitag/pen/WNKaJww

### Reproduction Steps

Open codepen and click on blue button.

### Reproduction Version

1.0.3

### Regression?

beta.98 for tooltip placement
beta.99 for using requestAnimation 

### Impact

high

### Esri team

ArcGIS Map Viewer

**Comment by macandcheese** [comment] 2023-02-01 02:00
Not 100% the same but similar enough to add - I have encountered this when a Tooltip referencing an Action is clicked and the containing Shell Panel has a Panel open as a result of that interaction. The previous Action tooltip will linger at the extent of the Shell Panel container: 

<img width="485" alt="Screen Shot 2023-01-31 at 8 50 02 PM" src="https://user-images.githubusercontent.com/4733155/215926126-3f72ce50-b9de-4276-8b7e-133f7d2e1c58.png">

I use `setFocus()` (without timeout) on the Panel, and when the Panel closes, to return focus to the Action. It's a bit unpredictable, as it works most of the time but you can occasionally see it while navigating via the Action Bar items in the component sample on the documentation site.

**Comment by jcfranco** [comment] 2023-02-07 00:40
FWIW, I narrowed down the regression to [this commit](https://github.com/Esri/calcite-components/commit/f490e5ee0a4ae75f0e3b727f4ce0f7925bc8e53c). I'll keep digging after I wrap some issues we've got queued for our patch release.

**Comment by jcfranco** [comment] 2023-02-07 00:41
@macandcheese On the surface, this does look related to this issue (where `setFocus()` doesn't trigger tooltip positioning`).

**Comment by AdelheidF** [comment] 2023-02-07 20:56
I can make it work now 90% of the time with this workaround for my custom components wrapping a calcite-flow-item. Focus and tooltip placement is mostly correct. 200ms is not too noticeable to the user.

```
componentDidLoad(): void {    
  setTimeout(() => requestAnimationFrame(() => flowItemNode.setFocus()), 200);
}
```

I noticed that the tooltip location issue only happens when the flow is inside a shell-panel. If it's inside a popover it seems to work fine.

I don't really understand why the back action gets the tooltip automatically when we add a second flow-item to a flow. At this point the mouse does not hover over the back action. If I then use the keyboard only to navigate around and come back to the back action the tooltip does not appear. So it's not that a focus of the back action always make the tooltip appear. After the initial appearance of that tooltip I only seem to get it to appear if I hover over with the mouse, which makes sense then.
-> I'd like to not have this initial tooltip of the back action.

**Comment by brittneytewks** [comment] 2023-02-27 17:47
Removed "needs triage" since a priority is set and estimate is indicated

**Comment by AdelheidF** [comment] 2023-04-12 16:29
what's the status on this one?

**Comment by jcfranco** [comment] 2023-04-12 16:47
No updates at this time.

**Comment by jcfranco** [comment] 2023-04-13 07:08
I forgot to share that we have some issues in the April milestone that could potentially help here, but I think we still need to dig around a bit. 

I know you found and shared a workaround for this. Does the priority/impact need to be adjusted or is it still a high-priority one?

**Comment by geospatialem** [comment] 2023-07-09 23:15
This looks mostly mitigated in `1.5.0-next.17`, @driskull is there a way to prevent the initialization of the `tooltip` placement? 

In this scenario is observed on the left hand of the screen for a split second prior to its proper placement on the back button.
![verify-back-flow-item-tooltip](https://github.com/Esri/calcite-design-system/assets/5023024/c3d6b3be-0f95-4fcb-b20d-0763b0d6f987)

**Comment by driskull** [comment] 2023-07-10 17:26
@geospatialem I don't think I can do anything about that since it happens because of the movement. Maybe a separate issue to track it?

**Comment by geospatialem** [comment] 2023-07-19 21:41
Might have had a bad connection while testing at the UC, this is working as-expected and intended. Marking as verified and complete. 🎉

**Comment by jcfranco** [comment] 2023-07-26 15:58
Closing per ☝️.

**Closed by jcfranco** 2023-07-26 15:58 UTC
Labels: bug, p - high, 4 - verified, ArcGIS Map Viewer, estimate - 3

**Comment by AdelheidF** [comment] 2023-08-03 21:30
> @geospatialem I don't think I can do anything about the tooltip positioning since it happens because of the movement. Maybe a separate issue to track it?

I still see the tooltip at the wrong location initially with `1.5.0-next.36`.
