### ISSUE TITLE
Epic - New Component: Table / Grid

### ISSUE THREAD

**Issue by MidasXIV** [Esri/calcite-design-system#1574] opened 2021-02-18 14:12 UTC
### Description
Add a functional table / grid component.

#### Phase I: Table - Simple functionality 
- [x] #6697
- [ ] https://github.com/Esri/calcite-design-system/issues/7630
- Design target: May 2023
- Target release: August 2023

#### Phase II: Table - Advanced functionality
- [ ] #6646 
- Design target: May 2023
- Target release: TBD

### Implementation
Design work will be carried out in May 2023, with a development target for the Table with simple functionality targeted for release in August 2023 and Table with advanced functionality TBD.

#### Mockup:
![image](https://user-images.githubusercontent.com/24829816/108369059-99317600-7214-11eb-91ac-a4d2197bb41e.png)

#### Pro:
![image](https://user-images.githubusercontent.com/24829816/108368974-8028c500-7214-11eb-8497-d7e39f370ed2.png)

**Comment by driskull** [comment] 2021-02-19 18:23
@mitc7862 @asangma what do you think?

**Comment by ope-nz** [comment] 2021-08-22 20:34
+1 a table component is vital to my product migration to calcite.

**Comment by AdelheidF** [comment] 2022-03-30 19:52
Current look on production.

![image](https://user-images.githubusercontent.com/44481292/160918561-9f1e41bc-6786-4aa9-a2fc-baba9315c511.png)

on a small screen
![image](https://user-images.githubusercontent.com/44481292/160919090-5ea91d9e-0987-4484-909d-5555f818df94.png)

Russian
![image](https://user-images.githubusercontent.com/44481292/160919356-e8979063-c2a8-4924-998f-9e7243838ef4.png)

RGB style for e.g. this layer:
https://tiledimageservices.arcgis.com/V6ZHFr6zdgNZuVG0/arcgis/rest/services/NLDAS2011_daily_wind_magdir/ImageServer

**Comment by shawnmgoulet** [comment] 2022-05-23 20:38
Some examples in the wild for this kind of component as per @macandcheese request:

https://mui.com/x/react-data-grid/row-grouping/

https://www.ag-grid.com/react-data-grid/grouping-group-rows/

https://web-components.carbondesignsystem.com/?path=/story/components-data-table--expandable

https://adazzle.github.io/react-data-grid/#/grouping

**Comment by macandcheese** [comment] 2022-05-23 20:44
Thanks @shawnmgoulet - @benelan / @geospatialem this is a v-next component, should we continue to use this issue for the time being?

**Comment by yelenakreyndel** [comment] 2022-06-17 17:18
@geospatialem please add a label "new component opportunity" and please CC me in all issues and conversations regarding opportunities for new components. Cc'ing @macandcheese and @benelan

**Comment by benelan** [comment] 2022-06-17 18:04
@yelenakreyndel we use the `new component` label which is already added.

**Comment by geospatialem** [comment] 2022-06-21 23:04
> @geospatialem please add a label "new component opportunity" and please CC me in all issues and conversations regarding opportunities for new components. Cc'ing @macandcheese and @benelan

@yelenakreyndel A notification has been added when the `new component` label is added to issues that will notify you (and others as you see fit in the future).

**Comment by yelenakreyndel** [comment] 2022-07-22 21:58
I'm going to assign this to @macandcheese to work on next.

**Comment by yelenakreyndel** [comment] 2022-07-28 16:21
@macandcheese Mitch needs this for Analysis.

**Comment by macandcheese** [comment] 2022-07-28 16:40
@jcfranco lets sync on this, I know there are many existing data grid libraries in use across the platform.

To scope the design requirements it would be good to understand what we would use if we go that route - it may be a case of theming an existing library. 

It would also likely provide us the complex capabilities like editable table cells, groups, multiple selection, freezing columns, reorder of columns, sorting, etc, etc.

**Comment by driskull** [comment] 2022-07-28 17:16
Agreed. It might be too much work to create our own grid component. Hopefully, we can decide on one to use with the ability to style it to match our design system.

**Comment by macandcheese** [comment] 2022-07-29 17:39
@yelenakreyndel this may be a research task to determine library, licensing, etc., before it moves to design, as the available UI to design / theme may differ.

**Comment by RSantosGIS** [comment] 2022-08-03 13:52
Adam T. suggested that the ArcGIS Knowledge Studio team +1 the requirement for a data-grid component.  Having a data grid is required for our project, and we have been asked to use Calcite wherever possible.  We are basically looking for something like the MUI data grid.

**Comment by paulcpederson** [comment] 2023-03-21 16:22
Does the August milestone does that mean we will be waiting until late summer for the data table component? We have a need for this component before that. This is the biggest hole in Calcite Components so I'd like to throw my +1 in and uplevel this in the queue if possible.

**Comment by yelenakreyndel** [comment] 2023-03-21 18:35
@paulcpederson Thank you for escalating this request. We are having a few discussions this week about understanding the effort for this work and potential blockers for the work to begin immediately. We'll follow up with you this week. 
Cc'ing @jcfranco

**Comment by yelenakreyndel** [comment] 2023-03-21 18:40
@geospatialem This component will need Design work. I added a Design label and added Adam as an assignee as Adam will work on Design for this component.

**Comment by yelenakreyndel** [comment] 2023-03-23 22:22
@paulcpederson Confirming that our plan is to deliver an MVP in August which is a a basic DataGrid that solves use cases documented here: https://confluencewikidev.esri.com/display/Calcite/DataGrid#DataGrid-Status (see Component Request Analysis). The team spoke and confirmed that delivering in August is what we plan on because @alisonailea would need to write code from scratch for this component.

**Comment by lingtangraster** [comment] 2023-06-24 02:14
@yelenakreyndel Hi Yelena, I am checking in when we will be able to see this new component? In August release (end of Aug.)? 
Thanks.

**Comment by xkov** [comment] 2023-06-26 06:18
Agree with @paulcpederson, this is a very important component to have. Looking forward to data-table/data-grid. Harry, Principle UI Designer at Esri Australia

**Comment by brittneytewks** [comment] 2023-07-06 17:20
@macandcheese added July milestone for post-UC work with the target of completion being in August.

**Comment by geospatialem** [comment] 2023-08-31 20:14
Simple table effort has been completed, the more advanced table will dictate the larger effort in a future milestone tbd. cc @brittneytewks

**Comment by geospatialem** [comment] 2023-09-06 15:40
Moving to November, where additional research will be performed for the next steps with the advanced table component.

**Comment by brittneytewks** [comment] 2023-12-11 13:45
Removed figma changes label, will track progress for this work in monday.com

**Comment by macandcheese** [comment] 2024-03-11 17:38
Closing this as the initial Table work is complete and further follow up and enhancements are logged as separate issues.

**Closed by macandcheese** 2024-03-11 17:38 UTC
Labels: new component, 1 - assigned, epic, ArcGIS Online, ArcGIS Web Analysis, needs milestone
