### ISSUE TITLE
Input Time Picker should allow a placeholder

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#9238] opened 2024-05-01 17:58 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As a developer I want to be able to set a placeholder consistent with Date Time Picker

### Acceptance Criteria

<calcite-inpute-time-picker placeholder=`${this.localeData.placeholder}` />

### Which Component

Input Time Picker

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment] 2024-09-26 17:59
Closing in favor of https://github.com/Esri/calcite-design-system/issues/6296 and https://github.com/Esri/calcite-design-system/issues/6585 in pursuit of more support through displaying and entering the time and customizing the time format.

**Closed by geospatialem** 2024-09-26 17:59 UTC
Labels: enhancement, 0 - new, needs triage, Calcite (design), impact - p3 - not time sensitive, calcite-components

**Comment by jcfranco** [comment] 2024-09-27 06:06
Just noticed the issues referenced above are specific to `input-date-picker`. This seems like a duplicate of https://github.com/Esri/calcite-design-system/issues/3671, though.
