### ISSUE TITLE
CCR don't fully load all components on initial load or refresh (f5)

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-design-system#7975] opened 2023-10-11 10:01 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calcite Components in React don't get completely loaded on the initial load. It's mostly icons that are directly not visible.
After saving the right file (containing the components) in VS Code, the page gets refreshed and the application shows all components.

Before (behavior after a f5 refresh):
![image](https://github.com/Esri/calcite-design-system/assets/25850072/14abadaf-e0d4-487a-a87c-e00964af1aac)
After (behavior after saving the `App.jsx` in VS Code:
![image](https://github.com/Esri/calcite-design-system/assets/25850072/73364960-1478-4289-9143-a86901726973)

### Expected Behavior

All components are shown as they should on the initial load.

### Reproduction Sample

https://github.com/arjanvanzutphen/ccr-initial-loading-issue

### Reproduction Steps

1. Clone the repo
2. Open the files in your IDE, I've used VS Code
3. Run `npm install` and `npm run dev`
4. A browser will show the page at, most likely http://localhost:5173
5. The banana icon is visible and the slider component is missing the 50 value on it's line.
6. Hit save (or ctrl+s) in VS Code and the icon becomes visible and the slider gets updated

### Reproduction Version

1.9.1

### Relevant Info

Edge (117), Chrome (116), Firefox (118)

### Regression?

-

### Priority impact

p3 - want for upcoming milestone

### Impact

Missing components results in debugging activities where a 'save' of a certain file would suffice, but it's not always clear which file

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Professional Services - Services Delivery

**Comment by DitwanP** [comment] 2023-11-29 16:45
@arjanvanzutphen So It looks like there was a duplicate of this issue that has reproduction instructions that shows the cause of this bug. #8143 

It looks like you have to make sure to import components from @esri/calcite-components in addition to the react wrappers like the sample on that issue does to mitigate this issue.

**Closed** 2023-11-29 17:03 UTC
Labels: bug, 1 - assigned, Professional Services - Services Delivery, p3 - want for upcoming milestone, calcite-components-react, spike
