### ISSUE TITLE
before open/close events emitted immediately after transition

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#9559] opened 2024-06-11 17:54 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

On `dev` - the Modal has the incorrect animation: 

https://github.com/Esri/calcite-design-system/assets/4733155/730fa810-248c-46cd-8041-c0874d621e04

### Expected Behavior

The animation should behave as it does in 2.9

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/dyEVmam?editors=1000

### Reproduction Steps

1. Open Codepen
2. Open Model
3. See difference in animation

### Reproduction Version

Unreleased

### Priority impact

impact - p1 - need for current milestone

### Impact

cc @jcfranco 

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by jcfranco** [comment] 2024-06-11 19:47
This was introduced by https://github.com/Esri/calcite-design-system/commit/bb45bdb24f70a397b2eeae02f90e719140423a92. It looks like it affects the `openClose` util and events will fire out of order. Bumped severity and marked as regression because of this.

**Comment by DitwanP** [comment] 2024-06-13 16:07
🍡 Verified locally on `dev`

**Closed by DitwanP** 2024-06-13 16:07 UTC
Labels: bug, p - high, 3 - installed, regression, Calcite (design), estimate - 2, impact - p1 - need for current milestone, calcite-components
