### ISSUE TITLE
[calcite-flow-item] does not have a back button if within a shadow root

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-design-system#6237] opened 2023-01-05 22:40 UTC
### Actual Behavior

With `showBackButton` being internal and defaulting to false, by default a flow item within a shadow root is missing the back button, breaking the functionality of a flow item.

### Expected Behavior

It should show a back button when it is the active flow item

### Reproduction Sample

https://codepen.io/eborgen/pen/vYaygZy

### Reproduction Steps

Observe that with a structure that puts a shadow root boundary between the `calcite-flow` and `calcite-flow-item`, the back button does not render.

### Reproduction Version

next.707

### Regression?

between beta.99 and next.707

### Impact

High - it breaks the workflow unless I set an internal prop and ignore the type error

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment] 2023-01-06 00:14
Could be related to the [utilities](https://github.com/esri/calcite-components/blob/f4a55a81cc087ab88e11b51e40ca6a37ed379e75/src/utils/dom.ts#L113-L154) used, will need a refactor in the component to mitigate without the use of the utility functions.

**Comment by jcfranco** [comment] 2023-01-25 07:44
@ethanbdev I could be misinterpreting the issue, but from what I can recall, `flow` never supported `flow-items` within the shadow DOM of extraneous components. Can you update your codepen or provide one that shows this behavior?

**Comment by ethanbdev** [comment] 2023-01-25 16:29
> @ethanbdev I could be misinterpreting the issue, but from what I can recall, `flow` never supported `flow-items` within the shadow DOM of extraneous components. Can you update your codepen or provide one that shows this behavior?

That makes sense, I think we are not using the flow-item quite correctly. But with the removal of the `showBackButton` attribute it made it not work at all. It could be reasonable to have a tree structure like:
```
<calcite-flow>
  <my-custom-component>
    <calcite-flow-item />
  </my-custom-component>
</calcite-flow>
```
If that is not supported we can adjust the structure or consider a different component, like a panel with a slotted action in the header.

**Comment by geospatialem** [comment] 2023-01-25 20:54
Allocating to the February release for further discussion.

**Comment by AdelheidF** [comment] 2023-01-26 19:52
Yes, I use this in a few places

![image](https://user-images.githubusercontent.com/44481292/214936257-4a0d9eb8-b318-4157-adce-be1244e494e2.png)

**Comment by ethanbdev** [comment] 2023-01-26 20:00
> @ethanbdev Gotcha. In the above structure snippet, is the item in the same light DOM tree as the flow? If so, I think that would work. I believe Map Viewer has some components structured similarly. @AdelheidF can you confirm?

It is not, all of our components utilize `shadow: true`

![image](https://user-images.githubusercontent.com/52869490/214937961-dd2c1018-5c09-4586-8df3-95e03cd5ac8c.png)
(I added `show-back-button` manually, ignoring the type error)

**Comment by jcfranco** [comment] 2023-03-04 03:10
@ethanbdev Thanks for the info and apologies for the belated reply. 😅 We'll need to revisit the timeline for this while we do some research on the approach. FWIW, we prototyped something that could be used as the base for this: https://github.com/Esri/calcite-components/issues/4817#issuecomment-1169443302. 

Did you find a workaround or is this still a high impact issue for you?

**Comment by AdelheidF** [comment] 2023-03-06 17:32
I would very much like to use `shadow: true` as well. Considering that we want to create all these custom flow-item wrapping components to be used everywhere they all run into this issue. I would still like to see this fixed.

If I don't use `shadow: false` the flow-items appear in a single panel underneath each other with 1.0.7.

**Comment by ethanbdev** [comment] 2023-03-06 17:47
I would say it has moved to a more moderate impact. The workaround is to use an undocumented, internal prop. We hope to change the structure of the components to not have the flow item in the shadow root, but I think it still felt like a regression when this behaviour changed

**Comment by johngalambos** [comment] 2023-03-08 22:01
It's possible I'm doing things wrong here, but with the calcite-components-react, I think the the flow item is always in a shadow root? And without the showBackButton attribute public anymore, I don't think it's possible to display a back button?

E.g. 
`function AreaSelector (props:NoSelectionProps) {

	return (
		<CalciteFlow>
		<CalciteFlowItem
			heading="Areas"
			closed={false}>
			<div className="esri-widget esri-widget--panel parcel-manager parcel-manager__panel-content">
				<div className="parcel-manager__panel-content__message">Select an area</div>
			</div>
		</CalciteFlowItem>
		</CalciteFlow>
	);
}
`

renders as:
![image](https://user-images.githubusercontent.com/1432130/223860524-96646229-e98c-4bae-a5bf-4696705f6cb3.png)

**Comment by driskull** [comment] 2023-04-28 00:07
I think we want to make sure parent/child components are within the same DOM and not separated by a shadowDOM so that they can work correctly.

I think even native elements need to be like this to work and are accessible.

I may be mistaken, but I don't think you can do a native `select` and child `options` in a shadowRoot.

**Comment by driskull** [comment] 2023-08-01 20:45
This issue should be marked as a feature request and not a bug. Parent/child components aren't designed to work across shadowDOM. If we need to support that, we should research it and decide if its something we want to support and if we can do so consistently. I lean towards not supporting this as it introduces a lot of complexity for querying inside another shadowRoot.

> I would very much like to use shadow: true as well. Considering that we want to create all these custom flow-item wrapping components to be used everywhere they all run into this issue. I would still like to see this fixed.

@AdelheidF It would be good for you to move to `shadow:true`.  I think `scoped` may be removed by Stencil at some point.

**Comment by jcfranco** [comment] 2023-09-01 17:33
@ethanbdev @AdelheidF `calcite-flow` now supports custom flow items (i.e., custom elements using shadow DOM that wrap a `calcite-flow-item`). There are 2 steps needed to have flow pick these custom items:

1. Set flow's `customItemSelectors`/`custom-item-selectors` to match the custom item element.
2. Update your custom item element to implement the [`FlowItemLike`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/flow/interfaces.ts#L3-L7) interface. The simplest approach would be to wrap a flow item, which I believe you already do.

Here's an example showing how you can do that with vanilla JS: https://codepen.io/jcfranco/pen/zYyBJEV. It should be much more straightforward w/ Stencil or similar tooling.

Note that the new prop and interface won't be available in the documentation until we have something covering custom element creation (no timeline on that). cc @geospatialem @macandcheese 

Let us know if you need any help or have any questions.

Happy coding! ✨💻✨

**Comment by geospatialem** [comment] 2023-09-01 18:30
Verified with the [Codepen mentioned in Franco's post](https://github.com/Esri/calcite-design-system/issues/6237#issuecomment-1703101262) above. ☝🏻

**Comment by AdelheidF** [comment] 2023-09-02 05:44
The `& HTMLElement` is giving me issues here
`export type FlowItemLikeElement = Pick<HTMLCalciteFlowItemElement, "beforeBack" | "menuOpen" | "setFocus" | "showBackButton"> & HTMLElement;`

`Class 'ArcgisSmartMappingGallery' incorrectly implements interface 'Pick<HTMLCalciteFlowItemElement, "beforeBack" | "menuOpen" | "setFocus" | "showBackButton"> & HTMLElement'.
Type 'ArcgisSmartMappingGallery' is not assignable to type 'HTMLElement'.
Type 'ArcgisSmartMappingGallery' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 285 more.ts(2420)`

**Comment by jcfranco** [comment] 2023-09-02 08:02
https://github.com/Esri/calcite-design-system/pull/7666 will split up the interface into:

* `FlowItemLike` – interface for classes to implement
* `FlowItemLikeElement` – interface for APIs of parent components supporting custom items

I've also added a Stencil-based example for custom flow items in my [previous comment](https://github.com/Esri/calcite-design-system/issues/6237#issuecomment-1703101262).

Technically, the custom item doesn't need to implement the interface for it to be picked up by flow, but it should to ensure APIs are in sync.

**Comment by jcfranco** [comment] 2023-09-05 19:45
#7666 landed! 🛬

@AdelheidF Would you be able to help verify once `1.7.1-next.3` (or greater) is deployed later today?

**Comment by AdelheidF** [comment] 2023-09-05 23:50
Seems good with `1.8.0-next.0`. Thanks!

**Comment by geospatialem** [comment] 2023-09-05 23:56
Closing per https://github.com/Esri/calcite-design-system/issues/6237#issuecomment-1707451957.

**Closed by geospatialem** 2023-09-05 23:56 UTC
Labels: enhancement, 4 - verified, p - medium, has workaround, ArcGIS Map Viewer

**Comment by jcfranco** [comment] 2023-09-06 18:59
@AdelheidF Thanks for testing! 🙌
