### ISSUE TITLE
Disabled buttons where the 'disabled' attribute is set dynamically are clickable in Firefox (React)

### ISSUE THREAD

**Issue by Jmendo12** [Esri/calcite-design-system#8203] opened 2023-11-17 20:50 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Similar to #7043, in Firefox when using the React wrapper, calcite-buttons which have their `disabled` attribute set dynamically can still be clicked when disabled.

### Expected Behavior

In Firefox, calcite-buttons with the React wrapper which are disabled dynamically cannot be clicked when disabled.

### Reproduction Sample

https://codesandbox.io/s/disabled-button-z2mmrd

### Reproduction Steps

1. **Load the sample in Firefox**
2. Check the "Disable Button" checkbox
3. Click the "Increment Count" button
4. Observe as the count is incremented when clicking the disabled button

### Reproduction Version

1.9.2

### Relevant Info

MacOS Sonoma, Firefox, React wrapper

### Priority impact

p4 - not time sensitive

### Impact

Currently working around this by using the recommended [workaround](https://github.com/Esri/calcite-design-system/issues/7043#issuecomment-1593217256) of checking if the button is disabled within the click handler.

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Realtime (ArcGIS Velocity)

**Comment by geospatialem** [comment] 2023-12-11 19:11
Spike to confirm workflow with Firefox, and expectation of the browser events. Determine if CC can provide a workaround, if needed, and to determine next steps.

**Comment by jcfranco** [comment] 2024-03-14 19:27
Closing as a duplicate of #8729. This is no longer an issue as of 2.5.0 (see [updated repro case](https://codesandbox.io/p/sandbox/calcite-components-dynamically-disabled-button-properly-works-in-ff-react-qlnw2r?file=%2Fsrc%2FApp.js%3A15%2C43)).

**Closed by jcfranco** 2024-03-14 19:27 UTC
Labels: bug, 0 - new, p4 - not time sensitive, calcite-components-react, spike, Realtime (ArcGIS Velocity)
