### ISSUE TITLE
Need events for Accordion

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-design-system#5985] opened 2022-12-10 14:42 UTC
### Description

Right now Accordion emits no events. There is no way to know if an item was expanded by the user.

### Acceptance Criteria

Accordion must emit `expandedStateChanged` event or something like this.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/accordion/

### Example Use Case

Need to track which item is currently expanded by the user. Is there a workaround for now?
If found that listening to `click` event on `accordion-item` does the trick, I just check if event.target === item itself.

### Esri team

ArcGIS Business/Community Analyst

**Comment by macandcheese** [comment] 2022-12-10 20:43
it might also be worth adding a read-only prop for expanded items similar to Dropdown: https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-selectedItems

**Comment by jcfranco** [comment] 2023-08-17 21:52
Closing as duplicate of https://github.com/Esri/calcite-design-system/issues/4531.

**Closed by jcfranco** 2023-08-17 21:52 UTC
Labels: enhancement, 0 - new, needs triage, ArcGIS Business/Community Analyst
