### ISSUE TITLE
Allow callbacks for clearable button on CalciteInput

### ISSUE THREAD

**Issue by nikki-lea** [Esri/calcite-design-system#6870] opened 2023-04-26 23:48 UTC
### Description

When 'clearable' is set on a Calcite Input, I'd like to be able to pass a callback to be run when the 'clear' button is clicked (so the state in the app can be reset).

### Acceptance Criteria

CalciteInput accepts a callback prop that is invoked when the user clicks the 'clear' button when 'clearable' is set to true.

### Which Component

CalciteInput

### Example Use Case

Currently requires reimplementing the clear button through use of CalciteAction - 

`            <CalciteInput
              icon="search"
              label={error ? "error" : "search"}
              onCalciteInputInput={debounce((e) => {
                setCurrentSearchText(e.target.value);
              })}
              onKeyUp={handleSubmit}
            >
              <CalciteButton
                onClick={() => {
                  setCurrentSearchText("");
                  resetSearchState();
                }}
                icon-start="x"
                slot="action"
                scale="m"
              ></CalciteButton>
            </CalciteInput>
`

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Enterprise

**Comment by jcfranco** [comment] 2023-04-27 17:31
Since clicking the clear button does the same thing as clearing the input yourself via selection, this should already be possible by using the `calciteInputChange` event (see https://codesandbox.io/s/zealous-ishizaka-ul28wk?file=/src/App.js).

**Comment by jcfranco** [comment] 2023-06-01 17:14
@nikki-lea Were you able to use the change event for your use case?

**Comment by nikki-lea** [comment] 2023-06-06 21:04
@jcfranco We need the user to be able to click into the box to edit their search without clearing it, so we just use our own implementation of a clear button to set the new search state instead.

**Comment by jcfranco** [comment] 2023-08-11 04:21
Apologies for the belated reply. Can you confirm the following are true (just making sure I'm following your use case):

1. When a users type characters, text search kicks in after a delay
2. When a user clears the typed in value with backspace and commits (`Enter` or blur event), search text is reset, but state remains unchanged
3. When a user clicks the clear button, the search text is cleared and state is reset

If so, what is the expected behavior when a user presses `Escape`? It has the same behavior as pressing the clear button.

FWIW, I've added a workaround to my example showing how you can detect when text has been cleared with the clear button (within a `calciteInputChange` event handler).

**Comment by jcfranco** [comment] 2023-08-18 17:05
Sharing some items from our conversation for posterity:

1. confirmed that the updated workaround is acceptable
2. from the component's perspective, there isn't any difference between clearing via backspace, Escape or the clear button and hence why I hesitate to add a dedicated event for this.
3. waiting on design's perspective to see how Escape plays into this

I'll close this based on 2, but feel free to reopen if an update to 3 confirms a need for this event.

**Closed by jcfranco** 2023-08-18 17:05 UTC
Labels: enhancement, 0 - new, needs triage, need more info, ArcGIS Enterprise, p4 - not time sensitive
