### ISSUE TITLE
calcite-block / calcite-sortable-list: Avatars fly in from left on Mac

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#7979] opened 2023-10-11 20:38 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Using Chrome on Mac when reordering calcite-blocks avatars fly in from the left.
It's fine on Windows.

Video that shows the issue here:
https://github.com/Esri/calcite-design-system/assets/44481292/6c37d88a-fc0a-4188-a636-663a37fb57e2

Matt discovered that it has something to do with the calcite-dropdown on the block headers.

cc @driskull 

### Expected Behavior

Same behavior on Mac and Windows.

### Reproduction Sample

https://codepen.io/afreitag/pen/eYKweaz

### Reproduction Steps

Reorder blocks on right panel.

### Reproduction Version

1.9.1

### Relevant Info

Mac, Chrome

### Priority impact

p2 - want for current milestone

### Impact

medium

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by driskull** [comment] 2023-10-12 21:35
This is because the `calcite-dropdown`'s `overlayPositioning`  is `fixed` and the dropdown menu is originally positioned in the top left corner because of this. When you drag the element, the whole element (including the menu which is in the top left corner) is being dragged. 

![Screenshot 2023-10-12 at 2 29 48 PM](https://github.com/Esri/calcite-design-system/assets/1231455/e7fe9d87-51f5-4fbc-9724-edd70678dfbb)

![Screenshot 2023-10-12 at 2 29 57 PM](https://github.com/Esri/calcite-design-system/assets/1231455/b5da2163-ef15-42d4-b7fd-1deb8481592c)

If you open the dropdown and then drag everything works fine because the component is now positioned correctly.

1. One solution is to remove the `open` check here so that the component is positioned correctly even when not open yet:
https://github.com/Esri/calcite-design-system/blob/8ea00eccee8ee6c40b0a1ae9992beb575247532f/packages/calcite-components/src/utils/floating-ui.ts#L424-L426
2. Another solution is to make sure the menu is `display:none` when not opened by adding that here. This may have unintended consequences though. https://github.com/Esri/calcite-design-system/blob/8ea00eccee8ee6c40b0a1ae9992beb575247532f/packages/calcite-components/src/utils/floating-ui.ts#L484-L492

CC @jcfranco for potential other solutions.

**Comment by jcfranco** [comment] 2023-10-12 22:25
@driskull Summing up our convo:

We can try solution 1 and test it out. Since `floating-ui` fixed perf in shadow DOM, I think we could always position it now. I believe this was the way it worked before the perf issue.

**Comment by AdelheidF** [comment] 2023-10-16 22:55
I created a codepen with the fix https://codepen.io/afreitag/pen/KKbjMYL

On Windows I can see the shadow of the avatar too far to the left on the second drag or any drag after that.

**Comment by driskull** [comment] 2023-10-16 23:15
It looks like the popover (used within calcite-dropdown) needs to call `reposition()` on connectedCallback. Its only calling it on `componenDidLoad()`.

Probably other components that have floating UI should do the same. We can reopen this one for me.

**Comment by geospatialem** [comment] 2023-10-18 06:46
@driskull Reassigned back to you, targeted for later this month.

**Comment by driskull** [comment] 2023-10-30 15:47
I need to research this a bit more. Once a drag happens the dropdown within the item is not repositioned correctly. Need to figure out why or what else we can do to get the position updated.

**Comment by driskull** [comment] 2023-11-03 22:52
Looked into this one a bit more. Seems like the positioning being calculated by floating-ui would be correct if the `overlayPositioning` was `absolute`. For some reason, when dragging the calculated position that gets computed is invalid for "fixed" but would be valid if the `overlayPositioning` was `absolute`.

Its as if its ignoring the fixed positioning after being dragged.

I can get it to position correctly if I set a timeout in the Dropdown's reposition method but nothing else has worked so far.

@jcfranco do you want to take a shot at it?

**Comment by jcfranco** [comment] 2023-11-15 19:25
Thanks for the breakdown! 👨‍🔬🔬

> @jcfranco do you want to take a shot at it?

I could look at this once I clear some items from my queue. Might be late in the week though. 

Triage-wise, could you add an estimate and priority for this? cc @brittneytewks @geospatialem

**Comment by driskull** [comment] 2023-11-15 19:28
Added estimate.

**Comment by jcfranco** [comment] 2023-11-20 16:56
@driskull Is this only affecting Windows? If not, can you share some info on how to reproduce? I don't see the issue with the above repro examples.

**Comment by driskull** [comment] 2023-11-20 17:27
@jcfranco repro steps

1. Open the codepen
2. Drag "Block B" in front of "Block A"
3. Notice how the positioning flys in from the right.
4. This only happens when there's a hidden floating ui inside the "Block B" or whatever. The floating ui positioning throws off the drag and drop.

 
![Nov-20-2023 09-25-55](https://github.com/Esri/calcite-design-system/assets/1231455/cdb0e64b-a5bf-45fa-b3e9-8462a4a253ea)

**Comment by driskull** [comment] 2023-11-20 18:01
Its affecting me on Mac, I havent' tested on windows but I would assume its an issue there as well.

**Comment by driskull** [comment] 2023-11-20 18:41
Opened this one since its related: https://github.com/Esri/calcite-design-system/issues/8214

**Comment by geospatialem** [comment] 2023-11-20 19:31
> Its affecting me on Mac, I havent' tested on windows but I would assume its an issue there as well.

@driskull Tested with Windows in Chrome, FF, and Safari and wasn't able to reproduce, so this appears to be specific to Mac.

**Comment by jcfranco** [comment] 2023-11-21 16:05
@driskull Thanks! I see the issue now.

> On Windows I can see the shadow of the avatar too far to the left **on the second drag or any drag after that**.

Not sure which steps I tried initially, but I can reproduce solidly now by following this key step (emphasis mine)☝️.

**Comment by driskull** [comment] 2023-11-21 18:17
@jcfranco I think the root cause of all this is #8214

**Comment by DitwanP** [comment] 2023-11-22 00:24
Verified locally on Main

https://github.com/Esri/calcite-design-system/assets/60022782/ecd4d2c0-23ca-4451-82e5-565e96504406

**Closed by DitwanP** 2023-11-22 00:24 UTC
Labels: bug, 4 - verified, ArcGIS Map Viewer, estimate - 5, p2 - want for current milestone, calcite-components

**Comment by AdelheidF** [comment] 2023-12-08 20:25
looks good to me too. Thanks!
