### ISSUE TITLE
[list] - unable to drag and drop list items successfully with nested lists

### ISSUE THREAD

**Issue by sagewall** [Esri/calcite-design-system#9521] opened 2024-06-05 14:35 UTC
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a list contains another list in a list-item and drag-enabled is true the list items fail to move as expected and the list becomes unresponsive when an item is dragged.

I think this was previously partially addressed with #8728 but the fix perhaps didn't address nested list items.

### Expected Behavior

The drag and drop behavior works on mobile devices using touch gestures with nested lists.

### Reproduction Sample

https://codepen.io/sagewall/pen/LYoyryy

### Reproduction Steps

1. Open this [codepen](https://codepen.io/sagewall/full/LYoyryy) on a mobile device
2. Expand the "Nested List Item"
3. Try to drag and drop any of the list items
4. Observe how the list becomes unresponsive or the list items fail to move

### Reproduction Version

2.8.3 and 2.9.0

### Relevant Info

Pixel 7, Chrome

### Priority impact

impact - p1 - need for current milestone

### Impact

This impacts the LayerList, BasemapLayerList, and TableList Javascript SDK widgets and the applications that use them like Map Viewer, Experience Builder and Instant Apps.

Also identified as a bug via `BUG-000167708`.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment] 2024-06-05 17:07
@jcfranco when we patched sortable, we patched it with my assumed fix but not the correct fix that went into Sortable. We may need to re-patch.

**Comment by driskull** [comment] 2024-06-05 17:09
Correct patch: https://github.com/SortableJS/Sortable/pull/2347/files

incorrect patch: https://github.com/Esri/calcite-design-system/blob/e26fce6c0a7fb3f37fd084176e8846e135df295b/patches/sortablejs%2B1.15.1.patch

**Comment by driskull** [comment] 2024-06-06 21:10
I can't reproduce this on my iphone or iphone simulator. Is it only on chrome on Pixel 7? Or can it be reproduced on an ios device?

**Comment by geospatialem** [comment] 2024-06-06 21:37
> I can't reproduce this on my iphone or iphone simulator. Is it only on chrome on Pixel 7? Or can it be reproduced on an ios device?

@driskull In this [example](https://codepen.io/sagewall/pen/LYoyryy) if you try to drag the nested item (the third item) containing additional nested items I was able to verify on my iPhone in Chrome: 

https://github.com/Esri/calcite-design-system/assets/5023024/2a7e1e65-21ee-43fa-abb7-f7aeafdc4dfd

**Comment by driskull** [comment] 2024-06-06 22:57
I can reproduce it in the codepen, even using chrome devtools with a mobile device enabled but I can't reproduce it with a local build.

**Comment by driskull** [comment] 2024-06-06 23:21
@jcfranco I can't reproduce it when the local server is running. However, If I do a build and copy the dist files I can reproduce it. Any ideas on why that might be? Some sort of minify or patch problem?

**Comment by driskull** [comment] 2024-06-13 03:52
Managed to reproduce and debug from a built copy. PR will be incoming shortly.

**Comment by geospatialem** [comment] 2024-06-20 20:56
Verified in `2.10.0-next.2` on iOS with Chrome:

https://github.com/Esri/calcite-design-system/assets/5023024/d7181df8-0b2b-46af-a8e2-6a61b4f38500

**Comment by geospatialem** [comment] 2024-06-20 22:35
Re-opening the above to mitigate the third party library recommended approach.

**Comment by geospatialem** [comment] 2024-06-24 14:41
Verified in `2.10.0-next.7` 🎉

**Closed by geospatialem** 2024-06-24 14:41 UTC
Labels: bug, 3 - installed, p - medium, ArcGIS Maps SDK for JavaScript, ArcGIS Experience Builder, ArcGIS Instant Apps, ArcGIS Map Viewer, impact - p1 - need for current milestone, calcite-components, spike

**Comment by sagewall** [comment] 2024-07-11 23:22
@geospatialem I think there may still be an issue with Android devices.  iOS may be okay but I'm seeing issues on my personal pixel 7 phone and multiple browserstack android phones using version 2.10.1

https://github.com/user-attachments/assets/cace8736-b729-436d-b4dd-5bc522c7dcb4

**Comment by geospatialem** [comment] 2024-07-12 14:03
@sagewall Thanks for reporting! @DitwanP can you work with Sage on creating a new related issue to tackle? Since its specific to Android devices, we'll need to determine the priority with the upcoming R3 release.
