### ISSUE TITLE
Combobox selectionMode single-persist allows de-selection

### ISSUE THREAD

**Issue by dnrr-fd** [Esri/calcite-design-system#10233] opened 2024-09-06 12:31 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The Combobox with selectionMode="single-persist" still shows the remove icon on the item.

### Expected Behavior

With selectionMode="single-persist" you should not be able to de-select the item.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/combobox/

### Reproduction Steps

1. https://developers.arcgis.com/calcite-design-system/components/combobox/
2. select selectionMode to single-persist
3. pick an item from the combobox
4. you can remove the item

![image](https://github.com/user-attachments/assets/100bddec-6466-4ba2-b4b7-5fc2ae185e30)

### Reproduction Version

2.12.1

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by dnrr-fd** [comment] 2024-09-06 12:36
This also happens in v2.11.1

**Comment by geospatialem** [comment] 2024-09-06 14:42
As a workaround you can use the `clear-disabled` attribute in combination with `selection-mode="single-persist"`:

```html
<calcite-combobox clear-disabled selection-mode="single-persist">
  ...
</calcite-combobox>
```

Related: #10163 

cc: @DitwanP for documentation consideration across the design system and its components

**Comment by dnrr-fd** [comment] 2024-09-06 14:52
> As a workaround you can use the `clear-disabled` attribute in combination with `selection-mode="single-persist"`:
> 
> ```
> <calcite-combobox clear-disabled selection-mode="single-persist">
>   ...
> </calcite-combobox>
> ```
> 
> Related: #10163
> 
> cc: @DitwanP for documentation consideration across the design system and its components

Thanks. That will help as I am stuck using 2.11.1 until my next revision.

**Comment by geospatialem** [comment] 2024-09-16 18:24
Duplicate of https://github.com/Esri/calcite-design-system/issues/10163

**Closed by geospatialem** 2024-09-16 18:24 UTC
Labels: bug, docs, 0 - new, needs triage, has workaround, impact - p1 - need for current milestone, calcite-components-react, calcite-components
