### ISSUE TITLE
Add "Lazy loading" ability for Combobox component

### ISSUE THREAD

**Issue by minhiu** [Esri/calcite-design-system#8558] opened 2024-01-05 00:36 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

- Combobox component should have the ability to lazy load its items. This is much needed for use cases where number of items is large (> 10000 items).
- Currently, when using Combobox with over 10000 items, the performance is poor and the app is unusable.

### Acceptance Criteria

- When enabled "Lazy loading", only render the visible items in the current view of the scroll.
- When having a large number of items (ex: > 10000), the performance should not be affected.

### Which Component

Combobox - https://developers.arcgis.com/calcite-design-system/components/combobox/

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Business/Community Analyst

**Comment by driskull** [comment] 2024-03-14 23:50
I think this could be a duplicate of #7384

**Comment by geospatialem** [comment] 2024-08-06 18:52
Duplicate of https://github.com/Esri/calcite-design-system/issues/6392, closing in favor of the effort and in coordination with the other related issue of https://github.com/Esri/calcite-design-system/issues/7384.

**Closed by geospatialem** 2024-08-06 18:52 UTC
Labels: enhancement, 0 - new, needs triage, ArcGIS Business/Community Analyst, impact - p2 - want for an upcoming milestone, calcite-components
