### ISSUE TITLE
[Tabs] Vertical scrollbar regression in Chromium browsers when housed inside a `panel`

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8139] opened 2023-11-07 15:48 UTC
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When `tabs` are housed inside a `panel` a scrollbar was introduced in `1.10.0`:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/bc024f70-d2e2-4536-8f29-7a4dcd2ba2fc)

### Expected Behavior

No scrollbar present in Chromium browsers.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/3e2eacc9-a123-4441-b394-cff02f9bef8f)

### Reproduction Sample

https://codepen.io/fcbasson/pen/rNPjPYM

### Reproduction Steps

1. Open the [sample](https://codepen.io/fcbasson/pen/rNPjPYM)
    - Also, can be observed in [this sample](https://codepen.io/geospatialem/pen/eYxgaqW)
2. Observe the scrollbar added into `tabs` in `1.10.0` 

### Reproduction Version

`1.10.0`

### Relevant Info

Effects Chromium browsers (Chrome, Edge on Windows). Firefox does not appear to be effected.

Presented in `1.10.0-next.11` with https://github.com/Esri/calcite-design-system/commit/e070d7db3f54c18c4586a558f3c0767fd1def3df when `tabs` are within a `panel`, could be related to the [`tab` section's `CSS.content` import](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/tab/tab.tsx#L72)?

### Regression?

1.10.0

### Priority impact

p4 - not time sensitive

### Impact

Visual regression.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment] 2023-11-08 14:58
This surfaced on [Community](https://community.esri.com/t5/calcite-design-system-questions/calcite-1-10-0-content-class-causing-overflow/m-p/1346551#M525) on 11/7/2023.

**Comment by timmorey** [comment] 2023-11-15 20:28
I'm seeing something that seems very similar, but my use case does not involve a `panel`, and it is reproducible across browsers (seeing in safari, firefox too).

In my case, I find that we get a small amount of unnecessary vertical scrolling anytime a `<calcite-tabs>` element has a fixed `height` assigned.  This behavior started showing up at 1.10.

For example: https://codepen.io/_timmorey_/pen/VwgrLPJ?editors=1100.  Notice that the tab content scrolls up/down a few px.  In contrast, if you switch the calcite references in that sample back to 1.9.2, the vertical scrolling goes away.

I can log a new issue for this if it would be helpful, but it sure sounds a lot like this issue.

**Comment by nwhittaker** [comment] 2023-11-17 17:59
Seeing this as well. For a suggested fix, adding a `box-sizing: border-box;` style to that `section.content` element in the `<calcite-tab>` element's shadow DOM seems to be enough.

**Comment by macandcheese** [comment] 2023-11-28 17:59
Running into this as well:

https://github.com/Esri/calcite-design-system/assets/4733155/33aed98e-cfa8-443a-b254-0df580544d1b

We could remove the built-in `block-padding` on the internal content container. This would prevent this scroll in the above use cases. 

This also leads to a more flexible component, since we aren't adding opinionated spacing to the top / bottom of tab content. Users could still achieve any current layout / padding by adding it to their slotted content.

**Comment by geospatialem** [comment] 2023-11-28 20:26
Updating the estimate to reflect the proposal from https://github.com/Esri/calcite-design-system/issues/8139#issuecomment-1830397218

**Comment by brittneytewks** [comment] 2023-12-11 13:42
Removed figma changes label, will track progress for this work in monday.com

**Comment by mpayson** [comment] 2023-12-12 03:06
I wonder if this is the same as https://github.com/Esri/calcite-design-system/issues/8091

**Comment by DitwanP** [comment] 2023-12-12 21:18
@driskull this looks like it fixed the scrolling issue for the original issue above, but just wanted to check that it wasn't also meant to fix any of the other ones that was mentioned in this thread right/
![Screenshot 2023-12-12 at 12 56 44 PM](https://github.com/Esri/calcite-design-system/assets/60022782/4d6d469c-73bb-466a-a48e-91eb0ed5bb68)

It also seems to have fixed [#8379](https://github.com/Esri/calcite-design-system/issues/8379)
![Screenshot 2023-12-12 at 1 02 29 PM](https://github.com/Esri/calcite-design-system/assets/60022782/04f495d2-6a5e-43ee-988e-19c34f367055)

The example that timmorey mentioned as well as the one mpayson referenced does not get resolved by this.

**Comment by driskull** [comment] 2023-12-12 21:19
@DitwanP did you mean to tag @eriklharper ?

**Comment by macandcheese** [comment] 2023-12-12 21:21
We should create an issue to track the creation of a `--calcite-tab-padding` (or whatever name). This would allow folks to easily override that - right now it's not able to be overwritten through any supported methods (read: you can do it by hacking into the shadowDOM, which we don't want folks to resort to).

**Comment by DitwanP** [comment] 2023-12-12 21:35
> @DitwanP did you mean to tag @eriklharper ?
![giphy](https://github.com/Esri/calcite-design-system/assets/60022782/19424fce-c798-453f-b879-f51cb22cba9d)

**Comment by eriklharper** [comment] 2023-12-13 22:35
> I wonder if this is the same as #8091 too?

This issue is not exactly the same as this one you referenced, but I did verify the fix I applied for #8139 also appears to have fixed #8091 too.

**Comment by DitwanP** [comment] 2023-12-13 23:14
🍠 Verified, screenshots in my last comment.

**Closed by DitwanP** 2023-12-13 23:14 UTC
Labels: bug, browser-edge, browser-chrome, 3 - installed, p - medium, regression, Calcite (dev), estimate - 2, p4 - not time sensitive, calcite-components
