### ISSUE TITLE
Bug: calcite-date-picker - selecting day activates previous day in certain cases

### ISSUE THREAD

**Issue by ChristopheSuter** [Esri/calcite-design-system#1863] opened 2021-03-30 15:55 UTC
### Summary
Selects previous day when click on Calendar. Screenshot click on March the 24th selects March the 23rd

### Reproduction Steps

1.

### Relevant Info 
![image](https://user-images.githubusercontent.com/78811924/113018515-ee9c6380-9180-11eb-8e7d-08a38217c995.png)

**Comment by caripizza** [comment] 2021-03-31 15:20
Hi @ChristopheSuter - do you have any information? Please provide your snippet of code, the calcite-components npm package version you're using, your browser version - anything to help us investigate this issue.

**Comment by ChristopheSuter** [comment] 2021-03-31 15:55
Hi, 
Here is some code
`<!DOCTYPE html>
<html>
<head>
     <meta charset="utf-8">
     
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
     <meta name="mobile-web-app-capable" content="yes">
     <meta name="apple-mobile-web-app-capable" content="yes">
     <meta name="apple-mobile-web-app-status-bar-style" content="default">
     <script type="module" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.esm.js"></script>
     <script nomodule="" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.js"></script>
     <link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.css" />
     
     <link rel="stylesheet" href="https://js.arcgis.com/4.18/esri/themes/light/main.css" />
     
</head>
<body>
     <div style="width: 400px">
          <calcite-date-picker scale="m" value="2020-12-12" min="2016-08-09" max="2023-12-18" locale="en"
               intl-next-month="Next month" intl-prev-month="Previous month"></calcite-date-picker>
     </div>
</body>
</html>`

**Comment by ChristopheSuter** [comment] 2021-03-31 16:01
Hi,
Here is a codepen, I am using latest version of Chrome 
https://codepen.io/christophesuter/pen/JjEEbYd

**Comment by caripizza** [comment] 2021-03-31 16:10
@ChristopheSuter I don't see the issue in your CodePen. How can I reproduce?

**Comment by ChristopheSuter** [comment] 2021-03-31 17:06
I have the same behavior in Chrome, Edge and FF, could this be linked to my locale (fr-ch) ?

**Comment by ChristopheSuter** [comment] 2021-03-31 17:13
Chrome Version 89.0.4389.90, Edge Version 89.0.774.63 (Official build) (64-bit) and FF 87.0 (64-bit)

**Comment by caripizza** [comment] 2021-03-31 18:29
@ChristopheSuter Based on what I know, you need to either set the document's `lang` attribute, or set the `locale` attribute on the calendar itself to see the proper locale data appear.

Here's an example via the 1st route: https://codepen.io/caripizza-the-animator/pen/GRrrmyy

(Note that CodePen doesn't allow access to higher-up elements like the `<html>` tag, so I went with a Javascript approach since `<html lang="fr-ch">` won't work in their pens.)

**Comment by paulcpederson** [comment] 2021-04-01 00:17
@caripizza most likely this is due to @ChristopheSuter 's time zone. @ChristopheSuter what time zone are you experiencing this issue in?

The easiest way to set timezone and debug on mac (without changing your whole OS) is to launch a new chrome instance passing a TZ config:

```
mkdir ~/chrome-profile
TZ='Asia/Shanghai' open -na "Google Chrome" --args "--user-data-dir=$HOME/chrome-profile"
```

The reason I think it may be time zone related is that if you select "today" and somebody is across the date line, it will be "tomorrow" and vice versa, just a guess though.

**Comment by ChristopheSuter** [comment] 2021-04-01 05:58
@caripizza I had already tried this, same problem, @paulcpederson I'm on a PC .. I am in Central European Time (GMT+2), in Switzerland

**Comment by ChristopheSuter** [comment] 2021-04-01 06:33
![image](https://user-images.githubusercontent.com/78811924/113252745-8191e680-92c4-11eb-9d9b-ab6d33fe0d97.png)
![image](https://user-images.githubusercontent.com/78811924/113252889-bb62ed00-92c4-11eb-8e88-c942b5b26a38.png)
I changed the Javascript Engine timeZone (to California) with that Chrome Extension, but still same behavior

**Comment by caripizza** [comment] 2021-04-01 15:30
@ChristopheSuter can you provide your snippet of code? The last CodePen you provided included `locale="en"` on the calendar component so I want to make sure that's not an issue.

**Comment by ChristopheSuter** [comment] 2021-04-01 15:55
@caripizza is this you need ? I updated it with locale='fr-ch' and your javascript ..
https://codepen.io/christophesuter/pen/JjEEbYd

**Comment by ChristopheSuter** [comment] 2021-04-21 06:41
Hi,
One more element: range date picker works fine. But still same problem with the simple one.
Best

**Comment by ChristopheSuter** [comment] 2021-05-10 12:40
@caripizza Hi, could you reproduce this problem ? It is still the same in latest version.

**Comment by sanjayng007** [comment] 2021-06-18 04:56
I am also experiencing the same issue with **calcite-input-date-picker**.
**Version: v1.0.0-beta.56**
**Timezone: India Standard Time (GMT+5:30)**

Using with Vue.js
```
<calcite-input-date-picker
    scale="s"
    :value="dateValue"
    :min="minVal"
    :max="maxVal"
    @calciteDatePickerChange="_setDate($event)"
>
</calcite-input-date-picker>
```


https://user-images.githubusercontent.com/17921952/122508382-8b9fc780-d01f-11eb-989d-dbb1fdf69986.mp4


https://user-images.githubusercontent.com/17921952/122508458-a83bff80-d01f-11eb-8448-f174367ec5af.mp4

**Comment by jcfranco** [comment] 2021-08-16 16:18
Assigning to @benelan for verification. 

@driskull Is this repro case sufficient for verification? https://github.com/Esri/calcite-components/issues/1863#issuecomment-812004213

**Comment by driskull** [comment] 2021-08-16 16:25
To verify, set your timezone to somewhere in europe and click around.

**Comment by benelan** [comment] 2021-08-16 16:35
I was able to repro the issue in the current release by changing my timezone. I can verify that the issue is fixed in next.

**Closed** 2024-05-24 23:29 UTC
Labels: bug

**Comment by eriklharper** [comment] 2024-05-24 23:33
Related to this, but in `input-date-picker` instead of just date-picker: https://github.com/Esri/calcite-design-system/issues/9422
