### ISSUE TITLE
Bug: Input Date Picker - user is able to input more than 4 numbers for the year

### ISSUE THREAD

**Issue by ankitagupta820** [Esri/calcite-design-system#2520] opened 2021-07-12 23:53 UTC
### Expected Behavior
For calcite-input type="date" or "datetime-local" the placeholder format shows mm/dd/yyyy. User should be able to enter 4 character long number for year, instead the user is able to input a 6-character number for year.
![image](https://user-images.githubusercontent.com/65870621/125369672-95bc9980-e331-11eb-956d-68235dd0b77e.png)

### Reproduction Steps or Sample
1. Create a calcite-component using calcite-input , with type="date" or "datetime-local".
2. On the app UI, observe the placeholder value i.e mm/dd/yyyy.
3. Year component accepts more than 4 characters.

### Relevant Info
Browser: Chrome, Safari, Edge

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment] 2022-03-15 22:00
This issue should be fixed for `calcite-input-date-picker` rather than `calcite-input`. The issue is reproducible in the doc sample: https://developers.arcgis.com/calcite-design-system/components/input-date-picker/#sample

**Comment by anveshmekala** [comment] 2022-05-06 21:19
Considering the native `<input type='date' />` element allow users to type 6 digits for year , do we need to support character length validation . Thoughts ? @macandcheese

**Comment by macandcheese** [comment] 2022-05-06 22:13
I generally prefer to match native, but I’m struggling to think of how having more than 4 digits is useful. 

The date picker doesn’t use the day/month/field masks like native date, correct? Maybe a good item to discuss next sync?

**Comment by anveshmekala** [comment] 2022-05-06 22:31
> I generally prefer to match native, but I’m struggling to think of how having more than 4 digits is useful.
> 
> The date picker doesn’t use the day/month/field masks like native date, correct? Maybe a good item to discuss next sync?

 Setting `max` attribute  for `input-date-picker` would  add mask for the date entered by the user . Any value greater would fallback to the maximum date allowed.  It still allows user to enter 6 digits before correcting the invalid values.

**Comment by yelenakreyndel** [comment] 2022-07-26 18:32
CC @ashetland

**Comment by geospatialem** [comment] 2024-04-30 23:11
Verified on form submission in `2.8.0-next.19` with [the following Codepen](https://codepen.io/geospatialem/pen/jORoLWq).

![image](https://github.com/Esri/calcite-design-system/assets/5023024/656a1886-88e1-4ba3-a797-88006ae70a44)

**Closed by geospatialem** 2024-04-30 23:11 UTC
Labels: bug, 4 - verified, p - medium
